//! UEFI bootloader — placeholder.
//! Will be implemented as an x86_64-unknown-uefi PE binary
//! that scans partition 1 for ISO files and presents a boot menu.

// Currently using the placeholder generated by build.rs.
// The real implementation will be compiled with:
//   cargo build --target x86_64-unknown-uefi
// and embedded here via include_bytes!.
