//! Stage2 BIOS bootloader — placeholder.
//! Will be implemented as a flat x86-16 real-mode binary
//! that scans partition 1 for ISO files and chainloads them.

// Currently using the placeholder generated by build.rs.
// The real implementation will be compiled as a separate
// binary target and embedded here via include_bytes!.