// ═══════════════════════════════════════════════════════════════════════════
//  ISO9660 directory parser + UEFI chainloader
// ═══════════════════════════════════════════════════════════════════════════
//
//  On pure UEFI systems (no CSM), the BIOS El Torito boot image cannot work
//  (no INT 13h, no legacy CD emulation).  The correct path is:
//    1. Parse ISO9660 Primary Volume Descriptor → get root directory
//    2. Walk /EFI/BOOT/ → find BOOTX64.EFI
//    3. Read it into a contiguous buffer
//    4. Call LoadImage() + StartImage()

use core::ffi::c_void;

use crate::disk::read_sector;
use crate::fs::{FsCtx, PayloadEntry, PayloadType, PAYLOAD_SLOT_COUNT};
use crate::output::{format_u64_buf, halt_or_reboot, print_dec, print_hex, print_raw};
use crate::protocol::{
    BlockIoProtocol, BootServices, LoadedImageProtocol, MemoryType, SystemTable,
    DevicePathProtocol, VirtualBlockIo, EFI_SUCCESS, LOADED_IMAGE_PROTOCOL_GUID,
};

use crate::locator::{FileBackedIsoLocator, IsoLocator};
use crate::strategy;

// Generated by build.rs from .czblignore in the repo root.
include!(concat!(env!("OUT_DIR"), "/premount_ignore.rs"));

// ═══════════════════════════════════════════════════════════════════════════
//  ISO9660 on-disk structures and helpers
// ═══════════════════════════════════════════════════════════════════════════

/// Read one 2048-byte ISO logical sector (4 × 512-byte disk sectors)
fn read_iso_sector(
    bio_ref: &BlockIoProtocol,
    bio_ptr: *mut BlockIoProtocol,
    mid: u32,
    iso_lba: u64,
    sector: u32,
    buf: &mut [u8; 2048],
) -> bool {
    let disk_lba = iso_lba + sector as u64 * 4;
    for i in 0..4usize {
        let mut sec = [0u8; 512];
        if !read_sector(bio_ref, bio_ptr, mid, disk_lba + i as u64, &mut sec) {
            return false;
        }
        buf[i * 512..(i + 1) * 512].copy_from_slice(&sec);
    }
    true
}

/// Read any size extent (LBA + byte length) into a heap buffer.
/// Caller must call `bs.free_pool` to release the allocation.
fn read_extent(
    bs: &mut BootServices,
    bio_ref: &BlockIoProtocol,
    bio_ptr: *mut BlockIoProtocol,
    mid: u32,
    iso_lba: u64,
    lba: u32,
    byte_len: u32,
) -> Option<(*mut u8, u32)> {
    let sector_count = ((byte_len as u64 + 2047) / 2048) as u32;
    let buf_len = sector_count as usize * 2048;

    let mut ptr: *mut c_void = core::ptr::null_mut();
    let status = unsafe {
        (bs.allocate_pool)(MemoryType::EfiLoaderData, buf_len, &mut ptr)
    };
    if status != EFI_SUCCESS || ptr.is_null() {
        return None;
    }
    let ptr_u8: *mut u8 = ptr as *mut u8;

    let disk_lba = iso_lba + lba as u64 * 4;
    let read_status = unsafe {
        (bio_ref.read_blocks)(bio_ptr, mid, disk_lba, buf_len, ptr)
    };
    if read_status != EFI_SUCCESS {
        unsafe { (bs.free_pool)(ptr); }
        return None;
    }
    Some((ptr_u8, byte_len.min(buf_len as u32)))
}

// ═══════════════════════════════════════════════════════════════════════════
//  ISO9660 directory walker
// ═══════════════════════════════════════════════════════════════════════════

fn get_root_dir(
    st: &mut SystemTable,
    bio_ref: &BlockIoProtocol,
    bio_ptr: *mut BlockIoProtocol,
    mid: u32,
    iso_lba: u64,
) -> Option<(u32, u32)> {
    let mut pvd = [0u8; 2048];
    if !read_iso_sector(bio_ref, bio_ptr, mid, iso_lba, 16, &mut pvd) {
        print_raw(st, b"Failed to read ISO PVD.\r\n\0");
        return None;
    }
    if pvd[0] != 1 || &pvd[1..6] != b"CD001" {
        print_raw(st, b"Invalid ISO PVD signature.\r\n\0");
        return None;
    }
    let root_extent = u32::from_le_bytes(pvd[158..162].try_into().unwrap());
    let root_size = u32::from_le_bytes(pvd[166..170].try_into().unwrap());
    Some((root_extent, root_size))
}

fn find_in_dir(
    bio_ref: &BlockIoProtocol,
    bio_ptr: *mut BlockIoProtocol,
    mid: u32,
    iso_lba: u64,
    dir_lba: u32,
    dir_size: u32,
    name: &[u8],
    scratch: &mut [u8; 2048],
) -> Option<(u32, u32)> {
    find_in_dir_with_loc(bio_ref, bio_ptr, mid, iso_lba, dir_lba, dir_size, name, scratch)
        .map(|(extent, size, _sector, _offset)| (extent, size))
}

fn find_in_dir_with_loc(
    bio_ref: &BlockIoProtocol,
    bio_ptr: *mut BlockIoProtocol,
    mid: u32,
    iso_lba: u64,
    dir_lba: u32,
    dir_size: u32,
    name: &[u8],
    scratch: &mut [u8; 2048],
) -> Option<(u32, u32, u32, u32)> {
    let total_sectors = ((dir_size as u64 + 2047) / 2048) as u32;
    for s in 0..total_sectors {
        if !read_iso_sector(bio_ref, bio_ptr, mid, iso_lba, dir_lba + s, scratch) {
            return None;
        }
        let mut offset: usize = 0;
        while offset + 34 <= 2048 && offset < (dir_size as usize).saturating_sub(s as usize * 2048) {
            let record_len = scratch[offset] as usize;
            if record_len == 0 { break; }
            if offset + record_len > 2048 { break; }
            let name_len = scratch[offset + 32] as usize;
            let name_offset = offset + 33;
            if name_offset + name_len > 2048 { break; }
            let effective_len = if name_len >= 2 && scratch[name_offset + name_len - 2] == b';' {
                name_len - 2
            } else {
                name_len
            };
            if effective_len == name.len() {
                let mut matched = true;
                for i in 0..name.len() {
                    let a = scratch[name_offset + i].to_ascii_uppercase();
                    let b = name[i].to_ascii_uppercase();
                    if a != b { matched = false; break; }
                }
                if matched {
                    let child_extent = u32::from_le_bytes(scratch[offset + 2..offset + 6].try_into().unwrap());
                    let child_size = u32::from_le_bytes(scratch[offset + 10..offset + 14].try_into().unwrap());
                    let dir_sector = dir_lba + s;
                    let byte_offset = offset as u32;
                    return Some((child_extent, child_size, dir_sector, byte_offset));
                }
            }
            offset += record_len;
        }
    }
    None
}

/// Scan a directory for the first non-directory entry that is safe to
/// overwrite (i.e. not ".", "..", or El Torito boot catalog files).
/// Returns (entry_sector, entry_offset, iso9660_name_bytes, effective_name_len).
fn find_first_file_in_dir(
    bio_ref: &BlockIoProtocol,
    bio_ptr: *mut BlockIoProtocol,
    mid: u32,
    iso_lba: u64,
    dir_lba: u32,
    dir_size: u32,
    scratch: &mut [u8; 2048],
) -> Option<(u32, u32, [u8; 16], usize)> {
    let total_sectors = ((dir_size as u64 + 2047) / 2048) as u32;
    for s in 0..total_sectors {
        if !read_iso_sector(bio_ref, bio_ptr, mid, iso_lba, dir_lba + s, scratch) {
            return None;
        }
        let mut offset: usize = 0;
        while offset + 34 <= 2048 && offset < (dir_size as usize).saturating_sub(s as usize * 2048) {
            let record_len = scratch[offset] as usize;
            if record_len == 0 { break; }
            if offset + record_len > 2048 { break; }
            let name_len = scratch[offset + 32] as usize;
            let name_offset = offset + 33;
            if name_offset + name_len > 2048 { break; }
            let flags = scratch[offset + 25];
            let is_dir = flags & 0x02 != 0;
            let is_dot = name_len == 1 && (scratch[name_offset] == 0 || scratch[name_offset] == 1);

            if !is_dot && !is_dir {
                let eff_len = if name_len >= 2 && scratch[name_offset + name_len - 2] == b';' {
                    name_len - 2
                } else {
                    name_len
                };
                if eff_len > 15 {
                    offset += record_len;
                    continue;
                }

                // Build uppercase name buffer for pattern matching
                let cl = eff_len.min(16);
                let mut upper = [0u8; 16];
                for i in 0..cl {
                    upper[i] = scratch[name_offset + i].to_ascii_uppercase();
                }

                // Skip El Torito boot catalog files — GRUB reads these on boot.
                let is_boot_catalog =
                    &upper[..cl] == b"BOOT.CATALOG"
                    || &upper[..cl] == b"BOOT.CAT";
                if is_boot_catalog {
                    offset += record_len;
                    continue;
                }

                // Skip .CFG files (grub.cfg, loopback.cfg etc.) — GRUB needs these.
                let has_cfg_ext = eff_len >= 4
                    && scratch[name_offset + eff_len - 4].to_ascii_uppercase() == b'.'
                    && scratch[name_offset + eff_len - 3].to_ascii_uppercase() == b'C'
                    && scratch[name_offset + eff_len - 2].to_ascii_uppercase() == b'F'
                    && scratch[name_offset + eff_len - 1].to_ascii_uppercase() == b'G';
                if has_cfg_ext {
                    offset += record_len;
                    continue;
                }

                // Skip EFI boot files — needed by the chainloaded shim/GRUB.
                let is_efi_boot =
                    &upper[..cl] == b"BOOTX64.EFI"
                    || &upper[..cl] == b"BOOTIA32.EFI";
                if is_efi_boot {
                    offset += record_len;
                    continue;
                }

                // Skip entries that match .czblignore patterns.
                let mut should_skip = false;
                for pat in PREMOUNT_IGNORE_PATTERNS {
                    if pat.is_prefix {
                        if cl >= pat.name.len() && &upper[..pat.name.len()] == pat.name {
                            should_skip = true;
                            break;
                        }
                    } else {
                        if cl == pat.name.len() && &upper[..cl] == pat.name {
                            should_skip = true;
                            break;
                        }
                    }
                }
                if should_skip {
                    offset += record_len;
                    continue;
                }

                let dir_sector = dir_lba + s;
                let dir_offset = offset as u32;
                return Some((dir_sector, dir_offset, upper, eff_len));
            }
            offset += record_len;
        }
    }
    None
}

/// Walk directory records using record_len to find the EOD byte position
/// (where record_len == 0 or the first byte after the last valid record).
/// Returns the EOD position as (absolute_iso_sector, byte_offset_within_sector)
/// and also writes the current root directory size (in bytes) into `dir_size_out`.
fn find_eod_in_dir(
    bio_ref: &BlockIoProtocol,
    bio_ptr: *mut BlockIoProtocol,
    mid: u32,
    iso_lba: u64,
    dir_lba: u32,
    dir_size: u32,
    scratch: &mut [u8; 2048],
    dir_size_out: &mut u32,
) -> Option<(u32, u32)> {
    let total_sectors = ((dir_size as u64 + 2047) / 2048) as u32;
    let mut walked = 0u32;
    for s in 0..total_sectors {
        if !read_iso_sector(bio_ref, bio_ptr, mid, iso_lba, dir_lba + s, scratch) {
            return None;
        }
        let mut off = 0usize;
        // walked already equals sector_base + off because both are
        // incremented by record_len in lockstep within each sector.
        // Using `walked + off` double-counts and inflates the root
        // directory size, causing GRUB to fail to find injected entries.
        while off < 2048 && walked < dir_size {
            let record_len = scratch[off] as usize;
            if record_len == 0 {
                // In ISO9660, record_len == 0 is also used as padding
                // at the end of a sector when the next record would
                // not fit.  Only treat it as the real EOD if this is
                // the last sector of the directory.
                if s + 1 == total_sectors {
                    // Actual EOD in the last sector.
                    // Check enough room: PREMOUNT.CPIO record = 46 bytes + 1 byte EOD = 47
                    if off + 47 <= 2048 {
                        *dir_size_out = walked;
                        return Some((dir_lba + s, off as u32));
                    }
                    // Not enough room in the last sector — caller must
                    // fall back to locating a real file to overwrite.
                    return None;
                }
                // Not the last sector — this is sector-end padding.
                // Skip to the next sector.
                break;
            }
            if record_len < 34 || off + record_len > 2048 {
                break; // malformed record, bail
            }
            walked += record_len as u32;
            off += record_len;
        }
        if s + 1 == total_sectors {
            // Last sector: make sure we have enough room for the
            // synthetic entry.  off == 2048 means the sector is full.
            if off + 47 <= 2048 {
                *dir_size_out = walked;
                return Some((dir_lba + s, off as u32));
            }
            return None;
        }
        walked = (s + 1) * 2048;
    }
    None
}

/// Build a complete ISO9660 directory record for "PREMOUNT.CPIO;1".
/// Returns the number of bytes written to `blob`.
fn build_premount_cpio_entry(
    blob: &mut [u8; 128],
    extent_lba: u32,
    file_size: u32,
) -> u32 {
    // ISO9660 directory record layout:
    //  0     : record length (1 byte)
    //  1     : extended attribute record length (1 byte, 0)
    //  2-5   : extent LBA (LE)
    //  6-9   : extent LBA (BE)
    //  10-13 : data length (LE)
    //  14-17 : data length (BE)
    //  18-24 : recording date/time (7 bytes, zeroed = 1970-01-01)
    //  25    : file flags (1 byte, 0 = plain file)
    //  26    : file unit size (1 byte, 0)
    //  27    : interleave gap size (1 byte, 0)
    //  28-31 : volume sequence number (LE, 1)
    //  32    : name length (1 byte)
    //  33+   : name bytes + optional padding + optional system use

    // Use "PREMOUNT.CPIO" without ";1" version suffix so GRUB's
    // ISO9660 driver matches the name exactly as it appears in the
    // patched grub.cfg initrd line.
    // "PREMOUNT.CPIO" = 13 bytes.  33 + 13 = 46 → already even, no padding needed.
    let name = b"PREMOUNT.CPIO";
    let name_len = name.len() as u8; // 13
    let record_len: u8 = 46;

    blob[0] = record_len;
    blob[1] = 0; // extended attr record len
    blob[2..6].copy_from_slice(&extent_lba.to_le_bytes());
    blob[6..10].copy_from_slice(&extent_lba.to_be_bytes());
    blob[10..14].copy_from_slice(&file_size.to_le_bytes());
    blob[14..18].copy_from_slice(&file_size.to_be_bytes());
    // Recording date: all zeros = 1900-01-01 (valid ISO9660)
    blob[18] = 0; blob[19] = 0; blob[20] = 0;
    blob[21] = 0; blob[22] = 0; blob[23] = 0; blob[24] = 0;
    blob[25] = 0; // flags: plain file
    blob[26] = 0; // file unit size
    blob[27] = 0; // interleave gap size
    blob[28..30].copy_from_slice(&1u16.to_le_bytes());
    blob[30..32].copy_from_slice(&1u16.to_be_bytes());
    blob[32] = name_len; // 13
    blob[33..33 + name.len()].copy_from_slice(name); // bytes 33–45

    // Append a new EOD marker byte right after this record
    blob[record_len as usize] = 0;

    (record_len as u32) + 1 // record (46) + EOD (1) = 47
}

fn find_efi_boot(
    st: &mut SystemTable,
    bio_ref: &BlockIoProtocol,
    bio_ptr: *mut BlockIoProtocol,
    mid: u32,
    iso_lba: u64,
) -> Option<(u32, u32, &'static [u8])> {
    let mut scratch = [0u8; 2048];
    let (root_lba, root_size) = get_root_dir(st, bio_ref, bio_ptr, mid, iso_lba)?;

    let candidates: &[&[u8]] = &[b"EFI"];
    let mut efi_dir = None;
    for &name in candidates {
        if let Some(v) = find_in_dir(bio_ref, bio_ptr, mid, iso_lba, root_lba, root_size, name, &mut scratch) {
            efi_dir = Some(v);
            break;
        }
    }
    let (efi_lba, efi_size) = efi_dir?;

    let boot_subdirs: &[&[u8]] = &[b"BOOT"];
    let mut boot_dir = None;
    for &name in boot_subdirs {
        if let Some(v) = find_in_dir(bio_ref, bio_ptr, mid, iso_lba, efi_lba, efi_size, name, &mut scratch) {
            boot_dir = Some(v);
            break;
        }
    }
    let (boot_lba, boot_size) = boot_dir?;

    let efi_names: &[&[u8]] = &[b"BOOTX64.EFI", b"BOOTIA32.EFI", b"GRUBX64.EFI", b"SHIMX64.EFI"];
    for &name in efi_names {
        if let Some(v) = find_in_dir(bio_ref, bio_ptr, mid, iso_lba, boot_lba, boot_size, name, &mut scratch) {
            return Some((v.0, v.1, name));
        }
    }

    // Debug: dump root directory content
    print_raw(st, b"[find_efi_boot] root_lba=\0");
    print_dec(st, root_lba as u64);
    print_raw(st, b" root_size=\0");
    print_dec(st, root_size as u64);
    print_raw(st, b" iso_lba=\0");
    print_dec(st, iso_lba);
    print_raw(st, b"\r\n\0");
    None
}

// ═══════════════════════════════════════════════════════════════════════════
//  .CFG patching helpers
// ═══════════════════════════════════════════════════════════════════════════

#[derive(Copy, Clone)]
struct CfgEntry {
    ext_lba: u32, ext_size: u32, dir_sector: u32, dir_offset: u32,
    path: [u8; 64], path_len: usize,
}

fn add_cfg_entry(
    entries: &mut [CfgEntry; 8],
    entry_count: &mut usize,
    ext_lba: u32, ext_size: u32, dir_sector: u32, dir_offset: u32,
    path: &[u8],
) {
    if *entry_count >= 8 { return; }
    for j in 0..*entry_count {
        if entries[j].ext_lba == ext_lba { return; }
    }
    let plen = path.len().min(63);
    let mut buf = [0u8; 64];
    buf[..plen].copy_from_slice(&path[..plen]);
    entries[*entry_count] = CfgEntry {
        ext_lba, ext_size, dir_sector, dir_offset,
        path: buf, path_len: plen,
    };
    *entry_count += 1;
}

fn try_patch_candidate(
    st: &mut SystemTable,
    bs: &mut BootServices,
    vb: &mut VirtualBlockIo,
    sfs_instance: *mut crate::iso_fs::IsoFsInstance,
    bio_ref: &BlockIoProtocol,
    bio_ptr: *mut BlockIoProtocol,
    mid: u32,
    iso_lba: u64,
    iso_name: &[u8],
    ext_lba: u32, ext_size: u32, dir_sector: u32, dir_offset: u32,
    iso_location: Option<&crate::locator::IsoLocation>,
    boot_kind: crate::boot_kind::BootKind,
) -> bool {
    let (orig_ptr, orig_len) = match read_extent(bs, bio_ref, bio_ptr, mid, iso_lba, ext_lba, ext_size) {
        Some(v) => v,
        None => return false,
    };
    let orig = unsafe { core::slice::from_raw_parts(orig_ptr, orig_len as usize) };

    let mut premount_target_name = [0u8; 16];
    let mut premount_target_name_len: usize = 0;
    if !sfs_instance.is_null() {
        let sfs = unsafe { &*sfs_instance };
        premount_target_name_len = sfs.ctx.premount_target_name_len;
        if premount_target_name_len > 0 && premount_target_name_len <= 16 {
            premount_target_name[..premount_target_name_len]
                .copy_from_slice(&sfs.ctx.premount_target_name[..premount_target_name_len]);
        }
    }

    let has_linux = (orig.len() >= 6 && orig.windows(6).any(|w| w == b"linux " || w == b"linux\t"))
        || (orig.len() >= 9 && orig.windows(9).any(|w| w == b"linuxefi " || w == b"linuxefi\t"));
    if !has_linux {
        unsafe { (bs.free_pool)(orig_ptr as *mut c_void); }
        return false;
    }

    let patch = strategy::patch_grub_cfg(
        orig,
        boot_kind,
        iso_name,
        iso_location,
        &premount_target_name[..premount_target_name_len],
        bs as *mut BootServices,
    );

    let (patched_buf, patched_size) = match patch {
        Some(p) if p.size != (orig_len as usize) || {
            let a = unsafe { core::slice::from_raw_parts(p.buf, p.size) };
            let b = unsafe { core::slice::from_raw_parts(orig_ptr, orig_len as usize) };
            a != b
        } => {
            unsafe { (bs.free_pool)(orig_ptr as *mut c_void); }
            (p.buf, p.size)
        }
        Some(p) => {
            // patch produced identical content — no change needed
            unsafe { (bs.free_pool)(p.buf as *mut c_void); }
            unsafe { (bs.free_pool)(orig_ptr as *mut c_void); }
            return false;
        }
        None => {
            unsafe { (bs.free_pool)(orig_ptr as *mut c_void); }
            return false;
        }
    };

    let sector_aligned_patch = ((patched_size + 2047) / 2048) * 2048;
    let mut patch_block_ptr: *mut c_void = core::ptr::null_mut();
    if unsafe { (bs.allocate_pool)(MemoryType::EfiLoaderData, sector_aligned_patch, &mut patch_block_ptr) } != EFI_SUCCESS || patch_block_ptr.is_null() {
        unsafe { (bs.free_pool)(patched_buf as *mut c_void); }
        return false;
    }
    let patch_dst = unsafe { core::slice::from_raw_parts_mut(patch_block_ptr as *mut u8, sector_aligned_patch) };
    patch_dst[..patched_size].copy_from_slice(unsafe { core::slice::from_raw_parts(patched_buf, patched_size) });
    for j in patched_size..sector_aligned_patch { patch_dst[j] = 0; }
    unsafe { (bs.free_pool)(patched_buf as *mut c_void); }

    let orig_end_sector = vb.media.bim_lb + 1;
    vb.patched_file_sector = orig_end_sector as u32;
    vb.patched_file_sectors = (sector_aligned_patch / 2048) as u32;
    vb.patched_file_buf = patch_block_ptr as *mut u8;
    vb.dir_entry_sector = dir_sector;
    vb.dir_entry_offset = dir_offset;
    vb.dir_entry_new_extent = vb.patched_file_sector;
    vb.dir_entry_new_size = patched_size as u32;
    vb.dir_entry_patched = true;
    vb.media.bim_lb = orig_end_sector + vb.patched_file_sectors as u64 - 1;

    print_raw(st, b"[grub.cfg] PATCHED OK: orig=\0");
    print_dec(st, orig_len as u64);
    print_raw(st, b" -> new=\0");
    print_dec(st, patched_size as u64);
    print_raw(st, b"\r\n\0");
    true
}

fn patch_grub_cfg_blockio(
    st: &mut SystemTable,
    bs: &mut BootServices,
    vbio: *mut VirtualBlockIo,
    sfs_instance: *mut crate::iso_fs::IsoFsInstance,
    bio_ref: &BlockIoProtocol,
    bio_ptr: *mut BlockIoProtocol,
    mid: u32,
    iso_lba: u64,
    iso_name: &[u8],
    iso_location: Option<&crate::locator::IsoLocation>,
    boot_kind: crate::boot_kind::BootKind,
) {
    if vbio.is_null() { return; }
    let vb = unsafe { &mut *vbio };

    let mut pvd = [0u8; 2048];
    if !read_iso_sector(bio_ref, bio_ptr, mid, iso_lba, 16, &mut pvd) { return; }
    if pvd[0] != 1 || &pvd[1..6] != b"CD001" { return; }
    let root_lba = u32::from_le_bytes(pvd[158..162].try_into().unwrap());
    let root_size = u32::from_le_bytes(pvd[166..170].try_into().unwrap());
    let mut scratch = [0u8; 2048];

    let mut entries = [CfgEntry {
        ext_lba: 0, ext_size: 0, dir_sector: 0, dir_offset: 0,
        path: [0; 64], path_len: 0,
    }; 8];
    let mut entry_count = 0usize;

    let known_paths: [(&[u8], &[u8], &[u8], &[u8]); 7] = [
        (b"BOOT", b"GRUB",  b"GRUB.CFG",     b"/boot/grub/grub.cfg"),
        (b"BOOT", b"GRUB",  b"LOOPBACK.CFG", b"/boot/grub/loopback.cfg"),
        (b"BOOT", b"GRUB2", b"GRUB.CFG",     b"/boot/grub2/grub.cfg"),
        (b"BOOT", b"GRUB2", b"LOOPBACK.CFG", b"/boot/grub2/loopback.cfg"),
        (b"EFI",  b"BOOT",  b"GRUB.CFG",     b"/EFI/BOOT/grub.cfg"),
        (b"",     b"",      b"GRUB.CFG",     b"/grub.cfg"),
        (b"",     b"",      b"GRUB.CFG",     b"/grub2/grub.cfg"),
    ];

    for (dir1, dir2, filename, path) in &known_paths {
        let entry = if dir1.is_empty() {
            find_in_dir_with_loc(bio_ref, bio_ptr, mid, iso_lba, root_lba, root_size, filename, &mut scratch)
        } else {
            let d1 = find_in_dir(bio_ref, bio_ptr, mid, iso_lba, root_lba, root_size, dir1, &mut scratch);
            if let Some(d1_entry) = d1 {
                let d2 = find_in_dir(bio_ref, bio_ptr, mid, iso_lba, d1_entry.0, d1_entry.1, dir2, &mut scratch);
                if let Some(d2_entry) = d2 {
                    find_in_dir_with_loc(bio_ref, bio_ptr, mid, iso_lba, d2_entry.0, d2_entry.1, filename, &mut scratch)
                } else { None }
            } else { None }
        };
        if let Some((ext_lba, ext_size, dir_sector, dir_offset)) = entry {
            add_cfg_entry(&mut entries, &mut entry_count, ext_lba, ext_size, dir_sector, dir_offset, path);
        }
    }

    if entry_count == 0 {
        let mut raw_entries: [(u32, u32, u32, u32); 32] = [(0,0,0,0); 32];
        let mut raw_count = 0usize;
        recursive_find_cfg_with_loc(
            bio_ref, bio_ptr, mid, iso_lba, root_lba, root_size,
            &mut scratch, &mut raw_entries, &mut raw_count, 0,
        );
        for i in 0..raw_count {
            let (ext_lba, ext_size, dir_sector, dir_offset) = raw_entries[i];
            if ext_size == 0 { continue; }
            add_cfg_entry(&mut entries, &mut entry_count, ext_lba, ext_size, dir_sector, dir_offset, b"/<recursive>.cfg");
        }
    }

    if entry_count == 0 {
        print_raw(st, b"[grub.cfg] No .CFG files found in ISO.\r\n\0");
        return;
    }

    for i in 0..entry_count {
        if try_patch_candidate(st, bs, vb, sfs_instance, bio_ref, bio_ptr, mid, iso_lba, iso_name,
            entries[i].ext_lba, entries[i].ext_size,
            entries[i].dir_sector, entries[i].dir_offset,
            iso_location, boot_kind) {
            return;
        }
    }
    print_raw(st, b"[grub.cfg] No patchable .CFG found (none have 'linux' line).\r\n\0");
}

fn recursive_find_cfg_with_loc(
    bio_ref: &BlockIoProtocol,
    bio_ptr: *mut BlockIoProtocol,
    mid: u32,
    iso_lba: u64,
    dir_lba: u32,
    dir_size: u32,
    scratch: &mut [u8; 2048],
    entries: &mut [(u32, u32, u32, u32); 32],
    entry_count: &mut usize,
    depth: usize,
) {
    if depth > 16 || *entry_count >= 32 { return; }
    let total_sectors = ((dir_size as u64 + 2047) / 2048) as u32;
    for s in 0..total_sectors {
        if !read_iso_sector(bio_ref, bio_ptr, mid, iso_lba, dir_lba + s, scratch) { return; }
        let mut offset: usize = 0;
        while offset + 34 <= 2048 && offset < (dir_size as usize).saturating_sub(s as usize * 2048) {
            let record_len = scratch[offset] as usize;
            if record_len == 0 { break; }
            if offset + record_len > 2048 { break; }
            let name_len = scratch[offset + 32] as usize;
            let name_offset = offset + 33;
            if name_offset + name_len > 2048 { break; }
            let flags = scratch[offset + 25];
            let is_dir = flags & 0x02 != 0;
            let extent = u32::from_le_bytes(scratch[offset + 2..offset + 6].try_into().unwrap());
            let size = u32::from_le_bytes(scratch[offset + 10..offset + 14].try_into().unwrap());

            let skip = name_len == 1 && (scratch[name_offset] == 0 || scratch[name_offset] == 1);
            if !skip {
                let eff_len = if name_len >= 2 && scratch[name_offset + name_len - 2] == b';' {
                    name_len - 2
                } else {
                    name_len
                };
                let has_cfg = eff_len >= 4 && {
                    let ofs = name_offset + eff_len - 4;
                    scratch[ofs] == b'.' && (scratch[ofs+1] | 0x20) == b'c'
                        && (scratch[ofs+2] | 0x20) == b'f' && (scratch[ofs+3] | 0x20) == b'g'
                };
                if has_cfg && !is_dir && *entry_count < 32 {
                    let mut dup = false;
                    for j in 0..*entry_count { if entries[j].0 == extent { dup = true; break; } }
                    if !dup {
                        entries[*entry_count] = (extent, size, dir_lba + s, offset as u32);
                        *entry_count += 1;
                    }
                }
                if is_dir && extent != dir_lba && *entry_count < 32 {
                    recursive_find_cfg_with_loc(bio_ref, bio_ptr, mid, iso_lba, extent, size, scratch, entries, entry_count, depth + 1);
                    if !read_iso_sector(bio_ref, bio_ptr, mid, iso_lba, dir_lba + s, scratch) { return; }
                }
            }
            offset += record_len;
        }
    }
}

// ═══════════════════════════════════════════════════════════════════════════
//  ISO scanner — detects BootKind from directory structure
// ═══════════════════════════════════════════════════════════════════════════

use crate::boot_kind::{name_matches, BootDescriptor, BootKind, BootloaderType};

/// Walk the ISO root directory and identify the distro family by checking
/// for well-known directories and files:
///   /casper/ → Casper (Ubuntu, Mint, Pop!_OS)
///   /live/   → DebianLive
///   /LiveOS/ → FedoraLive (Fedora, RHEL, CentOS)
///   /arch/   → ArchIso
///   /apks/ or /.alpine-release → Alpine
///   /sources/boot.wim → WindowsPE
///
/// Also checks for a GRUB config at standard paths to determine the
/// bootloader type.
pub fn scan_iso_structure(
    bio_ref: &BlockIoProtocol,
    bio_ptr: *mut BlockIoProtocol,
    mid: u32,
    iso_lba: u64,
    _bs: &mut BootServices,
) -> Option<BootDescriptor> {
    let mut pvd = [0u8; 2048];
    if !read_iso_sector(bio_ref, bio_ptr, mid, iso_lba, 16, &mut pvd) {
        return None;
    }
    if pvd[0] != 1 || &pvd[1..6] != b"CD001" {
        return None;
    }
    let root_lba = u32::from_le_bytes(pvd[158..162].try_into().unwrap());
    let root_size = u32::from_le_bytes(pvd[166..170].try_into().unwrap());

    let mut boot_kind = BootKind::Unknown;
    let mut scratch = [0u8; 2048];
    let total_sectors = ((root_size as u64 + 2047) / 2048) as u32;

    for s in 0..total_sectors {
        if !read_iso_sector(bio_ref, bio_ptr, mid, iso_lba, root_lba + s, &mut scratch) {
            break;
        }
        let mut offset: usize = 0;
        while offset + 34 <= 2048 && offset < (root_size as usize).saturating_sub(s as usize * 2048) {
            let record_len = scratch[offset] as usize;
            if record_len == 0 { break; }
            if offset + record_len > 2048 { break; }
            let name_len = scratch[offset + 32] as usize;
            let name_offset = offset + 33;
            if name_offset + name_len > 2048 { break; }
            let flags = scratch[offset + 25];
            let is_dir = flags & 0x02 != 0;

            let eff_len = if name_len >= 2 && scratch[name_offset + name_len - 2] == b';' {
                name_len - 2
            } else {
                name_len
            };
            let name = &scratch[name_offset..name_offset + eff_len];

            if boot_kind == BootKind::Unknown {
                if is_dir {
                         if name_matches(name, b"CASPER")  { boot_kind = BootKind::Casper; }
                    else if name_matches(name, b"LIVE")    { boot_kind = BootKind::DebianLive; }
                    else if name_matches(name, b"LIVEOS")  { boot_kind = BootKind::FedoraLive; }
                    else if name_matches(name, b"ARCH")    { boot_kind = BootKind::ArchIso; }
                    else if name_matches(name, b"APKS")    { boot_kind = BootKind::AlpinePremount; }
                } else {
                         if name_matches(name, b".ALPINE-RELEASE") { boot_kind = BootKind::AlpinePremount; }
                    else if name_matches(name, b".ALPINE_RELEASE") { boot_kind = BootKind::AlpinePremount; }
                    else if name_matches(name, b"BOOT.WIM")        { boot_kind = BootKind::WindowsPE; }
                }
            }
            offset += record_len;
        }
    }

    let mut bootloader = BootloaderType::Grub;
    let grub_paths: [&[&[u8]]; 3] = [
        &[b"BOOT", b"GRUB",  b"GRUB.CFG"],
        &[b"BOOT", b"GRUB2", b"GRUB.CFG"],
        &[b"EFI",  b"BOOT",  b"GRUB.CFG"],
    ];
    let mut found_grub = false;
    for path in &grub_paths {
        if path_exists(bio_ref, bio_ptr, mid, iso_lba, root_lba, root_size, path, &mut scratch) {
            found_grub = true;
            break;
        }
    }
    if !found_grub {
        bootloader = BootloaderType::None_;
    }

    Some(BootDescriptor { boot_kind, bootloader })
}

fn path_exists(
    bio_ref: &BlockIoProtocol,
    bio_ptr: *mut BlockIoProtocol,
    mid: u32,
    iso_lba: u64,
    root_lba: u32,
    root_size: u32,
    components: &[&[u8]],
    scratch: &mut [u8; 2048],
) -> bool {
    let (mut cur_lba, mut cur_size) = (root_lba, root_size);
    for &comp in components {
        match find_in_dir(bio_ref, bio_ptr, mid, iso_lba, cur_lba, cur_size, comp, scratch) {
            Some((lba, size)) => { cur_lba = lba; cur_size = size; }
            None => return false,
        }
    }
    true
}

// ═══════════════════════════════════════════════════════════════════════════
//  DevicePath builder
// ═══════════════════════════════════════════════════════════════════════════

fn build_iso_device_path(bs: &mut BootServices, iso_size_bytes: u64, efi_filename: &[u8]) -> *mut c_void {
    const CDROM_NODE: [u8; 24] = {
        let mut n = [0u8; 24];
        n[0] = 0x04; n[1] = 0x02; n[2] = 24; n[3] = 0;
        n
    };

    // Build UTF-16 path dynamically from the matched EFI filename
    let mut file_name = [0u16; 32];
    let mut idx = 0;
    // \EFI\BOOT\
    for &ch in b"\\EFI\\BOOT\\" {
        file_name[idx] = ch as u16;
        idx += 1;
    }
    // Append the EFI filename (e.g., BOOTX64.EFI, BOOTIA32.EFI)
    for i in 0..efi_filename.len().min(32 - idx - 1) {
        file_name[idx] = efi_filename[i] as u16;
        idx += 1;
    }
    // Null terminator
    file_name[idx] = 0;
    idx += 1;

    const END_NODE: [u8; 4] = [0x7F, 0xFF, 0x04, 0x00];

    let file_body_bytes = idx * 2;
    let total = CDROM_NODE.len() + 4 + file_body_bytes + END_NODE.len();
    let mut ptr: *mut c_void = core::ptr::null_mut();
    if unsafe { (bs.allocate_pool)(MemoryType::EfiLoaderData, total, &mut ptr) } != EFI_SUCCESS || ptr.is_null() {
        return core::ptr::null_mut();
    }
    let dp = ptr as *mut u8;
    unsafe {
        dp.copy_from_nonoverlapping(CDROM_NODE.as_ptr(), CDROM_NODE.len());
        *(dp.add(8) as *mut u64) = 0u64.to_le();
        // Partition Start — 0 for virtual CD-ROM backed by an ISO file.
        // On physical CD-ROM this is typically 16 (after the System Area).
        // Some firmware rejects the DevicePath if this field is set to the
        // ISO size (as was done previously), causing LoadImage to return
        // EFI_UNSUPPORTED.
        let partition_start = 0u64;
        *(dp.add(16) as *mut u64) = partition_start.to_le();
        let mut off = 24usize;
        dp.add(off).write_volatile(0x04u8); off += 1;
        dp.add(off).write_volatile(0x04u8); off += 1;
        *(dp.add(off) as *mut u16) = ((4 + file_body_bytes) as u16).to_le(); off += 2;
        core::ptr::copy_nonoverlapping(file_name.as_ptr() as *const u8, dp.add(off), file_body_bytes);
        off += file_body_bytes;
        dp.add(off).copy_from_nonoverlapping(END_NODE.as_ptr(), END_NODE.len());
    }
    ptr
}

/// Build a CD-ROM-only DevicePath (Media + End nodes, no File Path).
/// Used as a fallback when firmware rejects the synthetic file path node
/// but requires a DevicePath to locate the virtual CD-ROM handle.
fn build_cdrom_only_device_path(bs: &mut BootServices, _iso_size_bytes: u64) -> *mut c_void {
    const CDROM_NODE: [u8; 24] = {
        let mut n = [0u8; 24];
        n[0] = 0x04; n[1] = 0x02; n[2] = 24; n[3] = 0;
        n
    };
    const END_NODE: [u8; 4] = [0x7F, 0xFF, 0x04, 0x00];
    let total = CDROM_NODE.len() + END_NODE.len();
    let mut ptr: *mut c_void = core::ptr::null_mut();
    if unsafe { (bs.allocate_pool)(MemoryType::EfiLoaderData, total, &mut ptr) } != EFI_SUCCESS || ptr.is_null() {
        return core::ptr::null_mut();
    }
    let dp = ptr as *mut u8;
    unsafe {
        dp.copy_from_nonoverlapping(CDROM_NODE.as_ptr(), CDROM_NODE.len());
        *(dp.add(8) as *mut u64) = 0u64.to_le();
        *(dp.add(16) as *mut u64) = 0u64.to_le(); // Partition Start = 0
        dp.add(CDROM_NODE.len())
            .copy_from_nonoverlapping(END_NODE.as_ptr(), END_NODE.len());
    }
    ptr
}

// ═══════════════════════════════════════════════════════════════════════════
//  Boot dispatcher — routes to the correct boot method by payload type
// ═══════════════════════════════════════════════════════════════════════════

pub fn boot_payload_by_type(
    st: &mut SystemTable,
    image_handle: *mut c_void,
    disk_handle: *mut c_void,
    part1_lba: u64,
    payloads: &[PayloadEntry; PAYLOAD_SLOT_COUNT],
    idx: usize,
    bio_ref: &BlockIoProtocol,
    bio_ptr: *mut BlockIoProtocol,
    mid: u32,
) -> ! {
    if idx >= payloads.len() {
        print_raw(st, b"ERROR: payload index out of range.\r\n\0");
        halt_or_reboot(st);
    }
    let p = &payloads[idx];
    match p.payload_type {
        PayloadType::Iso => uefi_chainload_iso(st, image_handle, part1_lba, payloads, idx, bio_ref, bio_ptr, mid),
        PayloadType::Wim => boot_wim_payload(st, image_handle, part1_lba, payloads, idx, bio_ref, bio_ptr, mid),
        PayloadType::Vhd | PayloadType::Vhdx => boot_vhd_payload(st, image_handle, part1_lba, payloads, idx, bio_ref, bio_ptr, mid),
        PayloadType::Img => boot_img_payload(st, image_handle, part1_lba, payloads, idx, bio_ref, bio_ptr, mid),
        PayloadType::Efi => boot_efi_payload(st, image_handle, payloads, idx, bio_ref, bio_ptr, mid),
    }
}

// ═══════════════════════════════════════════════════════════════════════════
//  Generic payload boot stubs — full implementations to be added as needed
// ═══════════════════════════════════════════════════════════════════════════

fn boot_wim_payload(
    st: &mut SystemTable,
    _image_handle: *mut c_void,
    _part1_lba: u64,
    _payloads: &[PayloadEntry; PAYLOAD_SLOT_COUNT],
    _idx: usize,
    _bio_ref: &BlockIoProtocol,
    _bio_ptr: *mut BlockIoProtocol,
    _mid: u32,
) -> ! {
    print_raw(st, b"WIM boot: not yet implemented.\r\n\0");
    print_raw(st, b"  Windows PE / WIM boot requires a Windows Boot Manager\r\n\0");
    print_raw(st, b"  (bootmgfw.efi) on the ESP.  Place boot.wim and boot.sdi\r\n\0");
    print_raw(st, b"  alongside the WIM file and configure BCD manually.\r\n\0");
    halt_or_reboot(st);
}

fn boot_vhd_payload(
    st: &mut SystemTable,
    _image_handle: *mut c_void,
    _part1_lba: u64,
    _payloads: &[PayloadEntry; PAYLOAD_SLOT_COUNT],
    _idx: usize,
    _bio_ref: &BlockIoProtocol,
    _bio_ptr: *mut BlockIoProtocol,
    _mid: u32,
) -> ! {
    print_raw(st, b"VHD/VHDX boot: not yet implemented.\r\n\0");
    print_raw(st, b"  Virtual-disk boot requires converting the VHD to\r\n\0");
    print_raw(st, b"  a virtual BlockIo and chainloading a VHD-aware OS.\r\n\0");
    halt_or_reboot(st);
}

fn boot_img_payload(
    st: &mut SystemTable,
    _image_handle: *mut c_void,
    _part1_lba: u64,
    _payloads: &[PayloadEntry; PAYLOAD_SLOT_COUNT],
    _idx: usize,
    _bio_ref: &BlockIoProtocol,
    _bio_ptr: *mut BlockIoProtocol,
    _mid: u32,
) -> ! {
    print_raw(st, b"IMG boot: not yet implemented.\r\n\0");
    print_raw(st, b"  Raw disk-image boot requires creating a virtual BlockIo\r\n\0");
    print_raw(st, b"  and chainloading the image's EFI bootloader.\r\n\0");
    halt_or_reboot(st);
}

fn boot_efi_payload(
    st: &mut SystemTable,
    image_handle: *mut c_void,
    payloads: &[PayloadEntry; PAYLOAD_SLOT_COUNT],
    idx: usize,
    bio_ref: &BlockIoProtocol,
    bio_ptr: *mut BlockIoProtocol,
    mid: u32,
) -> ! {
    let p = &payloads[idx];
    let bs = unsafe { &mut *st.boot_services };
    let media_block_size = if !unsafe { (*bio_ptr).media }.is_null() {
        unsafe { (*(*bio_ptr).media).bim_bs }
    } else {
        512
    };
    let block_count = ((p.file_size + media_block_size as u64 - 1) / media_block_size as u64) as usize;
    let buf_size = block_count * media_block_size as usize;
    let mut buf_ptr: *mut c_void = core::ptr::null_mut();
    if unsafe { (bs.allocate_pool)(MemoryType::EfiLoaderData, buf_size, &mut buf_ptr) } != EFI_SUCCESS || buf_ptr.is_null() {
        print_raw(st, b"ERROR: Out of memory for EFI payload.\r\n\0");
        halt_or_reboot(st);
    }
    let status = unsafe {
        (bio_ref.read_blocks)(bio_ptr, mid, p.file_start_lba, buf_size, buf_ptr)
    };
    if status != EFI_SUCCESS {
        print_raw(st, b"ERROR: Failed to read EFI payload.\r\n\0");
        unsafe { (bs.free_pool)(buf_ptr); }
        halt_or_reboot(st);
    }

    print_raw(st, b"Booting EFI payload: \0");
    print_raw(st, &p.name[..p.name_len.min(120)]);
    print_raw(st, b" ...\r\n\0");

    let mut child_handle: *mut c_void = core::ptr::null_mut();
    let load_status = unsafe {
        (bs.load_image)(false, image_handle, core::ptr::null_mut(),
            buf_ptr as *const u8, p.file_size, &mut child_handle)
    };
    if load_status != EFI_SUCCESS {
        print_hex(st, b"ERROR: LoadImage failed, status=0x", load_status as u64);
        print_raw(st, b"\r\n\0");
        unsafe { (bs.free_pool)(buf_ptr); }
        halt_or_reboot(st);
    }
    unsafe { (bs.free_pool)(buf_ptr); }

    let mut lip: *mut LoadedImageProtocol = core::ptr::null_mut();
    if unsafe { (bs.handle_protocol)(child_handle, &LOADED_IMAGE_PROTOCOL_GUID, &mut lip as *mut _ as _) } == EFI_SUCCESS && !lip.is_null() {
        unsafe {
            (*lip).device_handle = image_handle;
            (*lip).parent_handle = image_handle;
        }
    }
    print_raw(st, b"Starting EFI payload...\r\n\0");
    let result = unsafe { (bs.start_image)(child_handle, &mut 0u64, &mut core::ptr::null_mut::<u16>()) };
    print_hex(st, b"StartImage returned 0x", result as u64);
    print_raw(st, b"\r\n\0");
    halt_or_reboot(st);
}

// ═══════════════════════════════════════════════════════════════════════════
//  Main chainload entry
// ═══════════════════════════════════════════════════════════════════════════

fn uefi_chainload_iso(
    st: &mut SystemTable,
    image_handle: *mut c_void,
    part1_lba: u64,
    files: &[PayloadEntry; PAYLOAD_SLOT_COUNT],
    idx: usize,
    bio_ref: &BlockIoProtocol,
    bio_ptr: *mut BlockIoProtocol,
    mid: u32,
) -> ! {
    let iso_lba = files[idx].file_start_lba;
    let iso_size = files[idx].file_size;
    let bs = unsafe { &mut *st.boot_services };
    unsafe { (bs.set_watchdog_timer)(0, 0x10000, 0, core::ptr::null()); }
    let iso_name = &files[idx].name[..files[idx].name_len.min(files[idx].name.len())];
    let live_uuid = [0u8; 10];

    let cdrom_tuple = crate::virtual_blockio::create_virtual_cdrom(
        bs, st as *mut SystemTable, iso_lba, bio_ptr, mid, iso_size, iso_name, &live_uuid,
    );
    let (device_handle, cdrom_dp, vbio_ptr, sfs_instance) = match cdrom_tuple {
        Some((h, dp, vb, sfs)) => (h, dp, vb, sfs),
        None => {
            print_raw(st, b"ERROR: Failed to create virtual CD-ROM.\r\n\0");
            halt_or_reboot(st);
        }
    };

    // ── Scan ISO directory structure for boot kind detection ──────────
    let boot_desc = scan_iso_structure(bio_ref, bio_ptr, mid, iso_lba, bs);
    if let Some(ref desc) = boot_desc {
        if !sfs_instance.is_null() {
            let sfs = unsafe { &mut *sfs_instance };
            sfs.ctx.boot_kind = desc.boot_kind;
        }
    }
    let boot_kind = boot_desc.as_ref().map_or(crate::boot_kind::BootKind::Unknown, |d| d.boot_kind);

    // ── Build premount cpio (fixup type depends on boot_kind) ────────
    let premount_bundle = {
        let fixup = boot_kind.fixup_type();
        match fixup {
            crate::boot_kind::FixupType::Alpine =>
                crate::premount::prepare_alpine_initrd(bs, iso_lba - part1_lba, iso_name),
            crate::boot_kind::FixupType::AlpinePremount =>
                crate::premount::prepare_premount_initrd(bs, iso_lba - part1_lba, false, iso_name),
            crate::boot_kind::FixupType::Arch =>
                crate::premount::prepare_arch_initrd(bs, iso_lba - part1_lba, iso_name),
            crate::boot_kind::FixupType::WindowsPE => None,
            _ => {
                let needs_sr = boot_kind.needs_sr_mod();
                crate::premount::prepare_premount_initrd(bs, iso_lba - part1_lba, needs_sr, iso_name)
            }
        }
    };
    if premount_bundle.is_none() {
        print_raw(st, b"[premount] allocation failed, skipping\r\n\0");
    }

    // ── BlockIO premount injection ────────────────────────────────────
    if !vbio_ptr.is_null() && premount_bundle.is_some() {
        let vb = unsafe { &mut *vbio_ptr };
        let bundle = premount_bundle.as_ref().unwrap();
        // Only zero-fill up to the actual allocation boundary.
        // bundle.cpio_alloc_size is the real pool size; writing beyond
        // it would corrupt the UEFI pool heap.
        let alloc_size = bundle.cpio_alloc_size;
        {
            let dst = unsafe { core::slice::from_raw_parts_mut(bundle.cpio_buf, alloc_size) };
            dst[bundle.cpio_size..].fill(0);
        }
        // Effective cpio size (zero-padded to alloc_size, rounded to sectors)
        let premount_cpio_sectors = ((alloc_size as u64 + 2047) / 2048) as u32;
        let orig_end = vb.media.bim_lb + 1;
        vb.premount_file_sector = orig_end as u32;
        vb.premount_file_sectors = premount_cpio_sectors;
        vb.premount_file_buf = bundle.cpio_buf;
        vb.media.bim_lb = orig_end + premount_cpio_sectors as u64 - 1;

        let mut pvd = [0u8; 2048];
        if read_iso_sector(bio_ref, bio_ptr, mid, iso_lba, 16, &mut pvd)
            && pvd[0] == 1 && &pvd[1..6] == b"CD001"
        {
            let root_lba = u32::from_le_bytes(pvd[158..162].try_into().unwrap());
            let root_size = u32::from_le_bytes(pvd[166..170].try_into().unwrap());
            let mut scratch = [0u8; 2048];

            if let Some((dir_sector, dir_offset, name_buf, name_len)) =
                find_first_file_in_dir(bio_ref, bio_ptr, mid, iso_lba, root_lba, root_size, &mut scratch)
            {
                vb.premount_entry_sector = dir_sector;
                vb.premount_entry_offset = dir_offset;
                vb.premount_entry_new_extent = vb.premount_file_sector;
                vb.premount_entry_new_size = bundle.cpio_size as u32;
                vb.premount_entry_patched = true;

                if !sfs_instance.is_null() {
                    let sfs = unsafe { &mut *sfs_instance };
                    sfs.ctx.premount_cpio_buf = bundle.cpio_buf;
                    sfs.ctx.premount_cpio_size = bundle.cpio_size;
                    let tlen = name_len.min(15);
                    sfs.ctx.premount_target_name[..tlen].copy_from_slice(&name_buf[..tlen]);
                    sfs.ctx.premount_target_name_len = tlen;
                }

                print_raw(st, b"[premount] overwriting \0");
                print_raw(st, &name_buf[..name_len.min(15)]);
                print_raw(st, b" dir entry at sector=\0");
                print_dec(st, dir_sector as u64);
                print_raw(st, b" off=\0");
                print_dec(st, dir_offset as u64);
                print_raw(st, b" size=\0");
                print_dec(st, bundle.cpio_size as u64);
                print_raw(st, b" bytes\r\n\0");
            } else {
                // Fallback: inject a complete synthetic PREMOUNT.CPIO
                // directory record at the first EOD byte of the root directory.
                // GRUB reads ISO9660 directly from Block I/O, not via SFS, so
                // merely setting SFS premount fields is insufficient.
                //
                // Strategy: scan root dir for the EOD marker byte 0x00,
                // and overwrite it + subsequent bytes with a complete
                // ISO9660 directory record naming "PREMOUNT.CPIO;1".
                let mut new_root_size: u32 = 0;
                if let Some((eod_sector, eod_offset)) =
                    find_eod_in_dir(bio_ref, bio_ptr, mid, iso_lba, root_lba, root_size, &mut scratch, &mut new_root_size)
                {
                    let mut blob = [0u8; 128];
                    let blob_len = build_premount_cpio_entry(
                        &mut blob,
                        vb.premount_file_sector,
                        bundle.cpio_size as u32,
                    );
                    vb.premount_entry_sector = eod_sector;
                    vb.premount_entry_offset = eod_offset;
                    vb.premount_entry_injected_blob = blob;
                    vb.premount_entry_injected_size = blob_len;
                    vb.premount_entry_injected = true;
                    vb.premount_new_root_size = new_root_size + blob_len;

                    if !sfs_instance.is_null() {
                        let sfs = unsafe { &mut *sfs_instance };
                        sfs.ctx.premount_cpio_buf = bundle.cpio_buf;
                        sfs.ctx.premount_cpio_size = bundle.cpio_size;
                        sfs.ctx.premount_target_name = *b"PREMOUNT.CPIO___";
                        sfs.ctx.premount_target_name_len = 13;
                    }

                    print_raw(st, b"[premount] injected synthetic PREMOUNT.CPIO entry at sector=\0");
                    print_dec(st, eod_sector as u64);
                    print_raw(st, b" off=\0");
                    print_dec(st, eod_offset as u64);
                    print_raw(st, b"\r\n\0");
                } else {
                    // Root directory is full (no free space for EOD injection
                    // and no safe file to overwrite).  Relocate the entire
                    // root directory to a new contiguous extent at the end of
                    // the virtual CD-ROM, appending the synthetic PREMOUNT.CPIO
                    // entry.  GRUB's ISO9660 driver reads directories sequentially,
                    // so the relocated extent must be contiguous.
                    let root_sectors = ((root_size as u64 + 2047) / 2048) as u32;
                    // Extra sector for the synthetic entry if needed
                    let extra_sectors = if root_size % 2048 == 0 || root_size % 2048 + 47 > 2048 { 1u32 } else { 0u32 };
                    let relocated_sectors = root_sectors + extra_sectors;
                    let relocated_bytes = relocated_sectors as usize * 2048;

                    let mut relocated_ptr: *mut c_void = core::ptr::null_mut();
                    if unsafe { (bs.allocate_pool)(MemoryType::EfiLoaderData, relocated_bytes, &mut relocated_ptr) } != EFI_SUCCESS || relocated_ptr.is_null() {
                        print_raw(st, b"[premount] relocation alloc failed\r\n\0");
                    } else {
                        let reloc = unsafe { core::slice::from_raw_parts_mut(relocated_ptr as *mut u8, relocated_bytes) };
                        // Zero-fill first
                        for b in reloc.iter_mut() { *b = 0; }
                        // Copy all original root directory sectors
                        for s in 0..root_sectors {
                            let mut sec = [0u8; 2048];
                            if read_iso_sector(bio_ref, bio_ptr, mid, iso_lba, root_lba + s, &mut sec) {
                                let off = s as usize * 2048;
                                let copy = ((root_size as usize).saturating_sub(off)).min(2048);
                                reloc[off..off + copy].copy_from_slice(&sec[..copy]);
                            }
                        }
                        // Build the synthetic entry at the end of the relocated data
                        let insert_off = root_size as usize;
                        let mut blob = [0u8; 128];
                        let blob_len = build_premount_cpio_entry(
                            &mut blob,
                            vb.premount_file_sector,
                            bundle.cpio_size as u32,
                        );
                        reloc[insert_off..insert_off + blob_len as usize].copy_from_slice(&blob[..blob_len as usize]);
                        let new_root_size = insert_off as u32 + blob_len;

                        let relocated_start = (vb.media.bim_lb + 1) as u32;
                        vb.media.bim_lb = relocated_start as u64 + relocated_sectors as u64 - 1;
                        vb.premount_root_relocated = true;
                        vb.premount_root_buf = relocated_ptr as *mut u8;
                        vb.premount_root_buf_size = relocated_bytes;
                        vb.premount_root_sectors = relocated_sectors;
                        vb.premount_root_start_sector = relocated_start;
                        vb.premount_new_root_size = new_root_size;
                        vb.premount_entry_injected = false; // synthetic entry is in reloc, not a separate injected sector

                        if !sfs_instance.is_null() {
                            let sfs = unsafe { &mut *sfs_instance };
                            sfs.ctx.premount_cpio_buf = bundle.cpio_buf;
                            sfs.ctx.premount_cpio_size = bundle.cpio_size;
                            sfs.ctx.premount_target_name = *b"PREMOUNT.CPIO___";
                            sfs.ctx.premount_target_name_len = 13;
                        }

                        print_raw(st, b"[premount] root dir relocated to sector=\0");
                        print_dec(st, relocated_start as u64);
                        print_raw(st, b" sectors=\0");
                        print_dec(st, relocated_sectors as u64);
                        print_raw(st, b" new_root_size=\0");
                        print_dec(st, new_root_size as u64);
                        print_raw(st, b"\r\n\0");
                    }
                }
            }
        }
    }

    let locator = FileBackedIsoLocator::from_payload_entry(
        &files[idx],
        crate::protocol::Guid { d1: 0, d2: 0, d3: 0, d4: [0u8; 8] },
        1, part1_lba,
    );
    let iso_loc = locator.locate();

    patch_grub_cfg_blockio(st, bs, vbio_ptr, sfs_instance, bio_ref, bio_ptr, mid, iso_lba, iso_name,
        Some(&iso_loc), boot_kind);

    let (efi_lba, efi_size, efi_filename) = match find_efi_boot(st, bio_ref, bio_ptr, mid, iso_lba) {
        Some(v) => v,
        None => {
            print_raw(st, b"ERROR: /EFI/BOOT/BOOTX64.EFI not found in ISO.\r\n\0");
            halt_or_reboot(st);
        }
    };
    let (buf_ptr, buf_len) = match read_extent(bs, bio_ref, bio_ptr, mid, iso_lba, efi_lba, efi_size) {
        Some(v) => v,
        None => {
            print_raw(st, b"ERROR: Failed to read EFI executable.\r\n\0");
            halt_or_reboot(st);
        }
    };
    let device_path = build_iso_device_path(bs, iso_size, efi_filename);
    print_raw(st, b"Loading EFI image...\r\n\0");
    print_raw(st, b"EFI image size=\0");
    print_dec(st, buf_len as u64);
    print_raw(st, b" bytes\r\n\0");

    // Most firmware accepts the synthetic DevicePath; some (InsydeH2O,
    // APTIO V) reject it and require NULL when SourceBuffer is set.
    // Try the DevicePath first, then retry with NULL, then retry with
    // a CD-ROM-only DevicePath (no file path node) which some firmware
    // prefers over NULL.  Also retry on EFI_SECURITY_VIOLATION (some
    // firmware refuses external EFI binaries unless explicitly allowed).
    let mut child_handle: *mut c_void = core::ptr::null_mut();
    let mut load_status: usize;

    // Check whether a LoadImage status code is a "soft" error that
    // warrants retrying with a different DevicePath.
    fn is_soft_load_error(status: usize) -> bool {
        status == crate::protocol::EFI_INVALID_PARAMETER
            || status == crate::protocol::EFI_UNSUPPORTED
            || status == crate::protocol::EFI_SECURITY_VIOLATION
    }

    load_status = unsafe {
        (bs.load_image)(false, image_handle,
            device_path as *mut crate::protocol::DevicePathProtocol,
            buf_ptr, buf_len as u64, &mut child_handle)
    };
    print_hex(st, b"[LoadImage #1 (synthetic DP)] status=0x", load_status as u64);
    print_raw(st, b"\r\n\0");

    if is_soft_load_error(load_status) {
        // Retry with NULL DevicePath (firmware rejects synthetic path).
        load_status = unsafe {
            (bs.load_image)(false, image_handle, core::ptr::null_mut(),
                buf_ptr, buf_len as u64, &mut child_handle)
        };
        print_hex(st, b"[LoadImage #2 (NULL DP)] status=0x", load_status as u64);
        print_raw(st, b"\r\n\0");
    }

    if is_soft_load_error(load_status) {
        // Retry with CD-ROM-only DevicePath (no file path node).
        // Some firmware needs a real DevicePath to locate the
        // device, but rejects the synthetic file path.
        let cdrom_only_dp = build_cdrom_only_device_path(bs, iso_size);
        if !cdrom_only_dp.is_null() {
            load_status = unsafe {
                (bs.load_image)(false, image_handle,
                    cdrom_only_dp as *mut crate::protocol::DevicePathProtocol,
                    buf_ptr, buf_len as u64, &mut child_handle)
            };
            print_hex(st, b"[LoadImage #3 (CD-ROM DP)] status=0x", load_status as u64);
            print_raw(st, b"\r\n\0");
            if load_status != EFI_SUCCESS {
                unsafe { (bs.free_pool)(cdrom_only_dp); }
            }
        }
    }

    if is_soft_load_error(load_status) {
        // Last resort: try loading without SourceBuffer and DevicePath
        // both NULL (some firmware requires pure file-based discovery).
        load_status = unsafe {
            (bs.load_image)(false, image_handle, core::ptr::null_mut(),
                core::ptr::null(), 0, &mut child_handle)
        };
        print_hex(st, b"[LoadImage #4 (NULL DP, no buffer)] status=0x", load_status as u64);
        print_raw(st, b"\r\n\0");
    }

    if load_status != EFI_SUCCESS {
        print_hex(st, b"ERROR: LoadImage failed after all retries, status=0x", load_status as u64);
        print_raw(st, b"\r\nEFI size=\0");
        print_dec(st, buf_len as u64);
        print_raw(st, b" bytes\r\n\0");
        unsafe { (bs.free_pool)(buf_ptr as _); (bs.free_pool)(device_path); }
        halt_or_reboot(st);
    }
    unsafe { (bs.free_pool)(buf_ptr as _); }

    let mut lip: *mut LoadedImageProtocol = core::ptr::null_mut();
    if unsafe { (bs.handle_protocol)(child_handle, &LOADED_IMAGE_PROTOCOL_GUID, &mut lip as *mut _ as _) } == EFI_SUCCESS && !lip.is_null() {
        unsafe {
            (*lip).device_handle = device_handle;
            (*lip).file_path = device_path;
            (*lip).parent_handle = image_handle;
        }
    }
    print_raw(st, b"Press any key to start...\r\n\0");
    {
        let bs_ref = unsafe { &mut *st.boot_services };
        if !st.con_in.is_null() {
            let ci = unsafe { &mut *(st.con_in as *mut crate::protocol::SimpleTextInput) };
            loop {
                let mut k = crate::protocol::Key { sc: 0, uc: 0 };
                if unsafe { (ci.read_key_stroke)(ci as *mut _, &mut k) } == EFI_SUCCESS {
                    break;
                }
                unsafe { (bs_ref.stall)(100_000) };
            }
        }
    }
    print_raw(st, b"Starting...\r\n\0");
    let status = unsafe { (bs.start_image)(child_handle, &mut 0u64, &mut core::ptr::null_mut::<u16>()) };
    print_hex(st, b"StartImage returned 0x\0", status as u64);
    print_raw(st, b"\r\n\0");
    // Wait for key press so user can read the return value before possible reset
    print_raw(st, b"Press any key...\r\n\0");
    {
        let bs_ref = unsafe { &mut *st.boot_services };
        if !st.con_in.is_null() {
            let ci = unsafe { &mut *(st.con_in as *mut crate::protocol::SimpleTextInput) };
            loop {
                let mut k = crate::protocol::Key { sc: 0, uc: 0 };
                if unsafe { (ci.read_key_stroke)(ci as *mut _, &mut k) } == EFI_SUCCESS {
                    break;
                }
                unsafe { (bs_ref.stall)(100_000) };
            }
        }
    }
    if status != EFI_SUCCESS {
        print_raw(st, b"Press any key to reboot...\r\n\0");
        let bs_ref = unsafe { &mut *st.boot_services };
        if !st.con_in.is_null() {
            let ci = unsafe { &mut *(st.con_in as *mut crate::protocol::SimpleTextInput) };
            loop {
                let mut k = crate::protocol::Key { sc: 0, uc: 0 };
                if unsafe { (ci.read_key_stroke)(ci as *mut _, &mut k) } == EFI_SUCCESS {
                    break;
                }
                unsafe { (bs_ref.stall)(100_000) };
            }
        }
        halt_or_reboot(st);
    }
    // Child called ExitBootServices.  Never reboot.
    loop {
        unsafe { core::arch::asm!("hlt") }
    }
}

// ═══════════════════════════════════════════════════════════════════════════
//  Public API
// ═══════════════════════════════════════════════════════════════════════════

pub fn boot_iso(
    st: &mut SystemTable,
    image_handle: *mut c_void,
    _disk_handle: *mut c_void,
    part1_lba: u64,
    files: &[PayloadEntry; PAYLOAD_SLOT_COUNT],
    idx: usize,
    bio_ref: &BlockIoProtocol,
    bio_ptr: *mut BlockIoProtocol,
    mid: u32,
) {
    print_raw(st, b"\r\nBooting ISO (UEFI chainload)...\r\n\0");
    uefi_chainload_iso(st, image_handle, part1_lba, files, idx, bio_ref, bio_ptr, mid);
}

use crate::fs::scan_payloads;

pub fn show_payload_menu(
    st: &mut SystemTable,
    image_handle: *mut c_void,
    disk_handle: *mut c_void,
    payloads: &[PayloadEntry; PAYLOAD_SLOT_COUNT],
    count: usize,
    ctx: &FsCtx,
    bio_ref: &BlockIoProtocol,
    bio_ptr: *mut BlockIoProtocol,
    mid: u32,
) -> ! {
    if count == 0 {
        print_raw(st, b"\r\nNo bootable payloads found on partition 1.\r\n\0");
        halt_or_reboot(st);
    }
    print_raw(st, b"\r\n=== Choosable UEFI Boot Menu ===\r\n\0");
    for i in 0..count.min(10) {
        let (sb, sl) = format_u64_buf((i + 1) as u64);
        print_raw(st, b" "); print_raw(st, &sb[20 - sl..]); print_raw(st, b". ");
        if payloads[i].name_len > 0 && payloads[i].name[0] != 0 {
            print_raw(st, &payloads[i].name[..payloads[i].name_len]);
        }
        let (type_str, is_supported): (&[u8], bool) = match payloads[i].payload_type {
            PayloadType::Iso => (b" ISO ", true),
            PayloadType::Wim => (b" WIM  [unsupported]", false),
            PayloadType::Vhd => (b" VHD  [unsupported]", false),
            PayloadType::Vhdx => (b" VHDX [unsupported]", false),
            PayloadType::Img => (b" IMG  [unsupported]", false),
            PayloadType::Efi => (b" EFI ", true),
        };
        let size_mb = payloads[i].file_size / (1024 * 1024);
        let (sb2, sl2) = format_u64_buf(size_mb);
        print_raw(st, type_str);
        if is_supported {
            print_raw(st, b" ("); print_raw(st, &sb2[20 - sl2..]); print_raw(st, b" MiB)\r\n\0");
        } else {
            print_raw(st, b"\r\n\0");
        }
    }
    print_raw(st, b"Enter number to boot (or 'r' to scan): \0");

    use crate::protocol::{Key, SimpleTextInput};
    loop {
        let mut k = Key { sc: 0, uc: 0 };
        if !st.con_in.is_null() {
            let ci = unsafe { &mut *(st.con_in as *mut SimpleTextInput) };
            if unsafe { (ci.read_key_stroke)(ci as *mut _, &mut k) } != EFI_SUCCESS { continue; }
        }
        let ch = if k.uc >= 0x20 && k.uc < 0x7F { k.uc as u8 }
            else if k.uc == 0x0D || k.uc == 0x0A { b'\n' }
            else { 0 };
        if (b'1'..=b'9').contains(&ch) {
            let idx = (ch - b'1') as usize;
            if idx < count {
                let is_supported = matches!(payloads[idx].payload_type, PayloadType::Iso | PayloadType::Efi);
                if !is_supported {
                    print_raw(st, b"\r\nPayload type not yet implemented. Press any key to continue...\r\n\0");
                    continue;
                }
                boot_payload_by_type(st, image_handle, disk_handle, ctx.part1_lba, payloads, idx, bio_ref, bio_ptr, mid);
            }
        } else if ch == b'0' && count >= 10 {
            let is_supported = matches!(payloads[9].payload_type, PayloadType::Iso | PayloadType::Efi);
            if !is_supported {
                print_raw(st, b"\r\nPayload type not yet implemented. Press any key to continue...\r\n\0");
                continue;
            }
            boot_payload_by_type(st, image_handle, disk_handle, ctx.part1_lba, payloads, 9, bio_ref, bio_ptr, mid);
        } else if ch == b'r' || ch == b'R' {
            print_raw(st, b"\r\nRe-scanning...\r\n\0");
            let mut new_payloads: [PayloadEntry; PAYLOAD_SLOT_COUNT] = [PayloadEntry {
                name: [0; 256], name_len: 0, file_start_lba: 0, file_size: 0,
                payload_type: PayloadType::Iso,
            }; PAYLOAD_SLOT_COUNT];
            let mut new_count: usize = 0;
            scan_payloads(bio_ref, bio_ptr, mid, ctx, &mut new_payloads, &mut new_count);
            show_payload_menu(st, image_handle, disk_handle, &new_payloads, new_count, ctx, bio_ref, bio_ptr, mid);
        }
    }
}