//! Build script for choosable-efi.
//!
//! Reads `.czblignore` from the project root and emits
//! `$OUT_DIR/premount_ignore.rs` containing a static array of
//! `PremountIgnorePattern` entries used by `find_first_file_in_dir()`.

use std::env;
use std::fs;
use std::io::BufRead;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    // Walk up to the workspace root (three levels above efi/):
    //   <repo>/bootloader/efi/  → <repo>/bootloader/ → <repo>/
    let repo_root = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .expect("cannot find repo root");

    let ignore_path = repo_root.join(".czblignore");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let dest = out_dir.join("premount_ignore.rs");

    let mut patterns: Vec<(String, bool)> = Vec::new(); // (name, is_prefix)

    if let Ok(f) = fs::File::open(&ignore_path) {
        let reader = std::io::BufReader::new(f);
        for line in reader.lines() {
            let line = match line {
                Ok(l) => l,
                Err(_) => continue,
            };
            let trimmed = line.trim();
            // skip empty lines and comments
            if trimmed.is_empty() || trimmed.starts_with('#') {
                continue;
            }
            let is_prefix = trimmed.ends_with('*');
            let name = if is_prefix {
                &trimmed[..trimmed.len() - 1]
            } else {
                trimmed
            };
            if name.is_empty() {
                continue;
            }
            patterns.push((name.to_uppercase(), is_prefix));
        }
    } else {
        // If .czblignore doesn't exist, emit a warning and fall back to
        // hardcoded defaults.
        println!("cargo:warning=.czblignore not found at {}, using built-in defaults", ignore_path.display());
        patterns.push(("MD5SUM".into(), true));
        patterns.push(("README".into(), true));
        patterns.push(("UBUNTU".into(), true));
        patterns.push(("AUTORUN.INF".into(), false));
    }

    let mut code = String::new();
    code.push_str("// AUTO-GENERATED by build.rs from .czblignore — DO NOT EDIT\n");

    code.push_str("pub static PREMOUNT_IGNORE_PATTERNS: &[PremountIgnorePattern] = &[\n");
    for (name, is_prefix) in &patterns {
        // Emit byte string literal to avoid array-literal type issues
        let escaped = name.escape_default().to_string();
        code.push_str(&format!(
            "    PremountIgnorePattern {{ name: b\"{}\", is_prefix: {} }},\n",
            escaped, is_prefix
        ));
    }
    code.push_str("];\n");

    code.push_str(
        "\npub struct PremountIgnorePattern {\n\
         \x20   pub name: &'static [u8],\n\
         \x20   pub is_prefix: bool,\n\
         }\n",
    );

    fs::write(&dest, &code).unwrap_or_else(|e| {
        panic!("Failed to write {}: {}", dest.display(), e);
    });

    println!("cargo:rerun-if-changed={}", ignore_path.display());
    println!("cargo:rerun-if-changed=src/");
    println!("cargo:rerun-if-changed=build.rs");
}