//! Build script for choosable-efi.
//!
//! 1. Builds `premount-init` (static ELF for /init.choosable) via musl.
//! 2. Reads `.czblignore` → emits `premount_ignore.rs`.

use std::env;
use std::fs;
use std::io::BufRead;
use std::path::PathBuf;
use std::process::Command;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let repo_root = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .expect("cannot find repo root");

    // 1. Build premount-init binary (static musl, runs as /init.choosable)
    let premount_src = repo_root.join("bootloader/premount-init");
    let premount_bin = manifest_dir.join("premount-init.bin");

    if !premount_src.exists() {
        panic!("premount-init source directory not found at: {}", premount_src.display());
    }

    // Determine target directory: prefer CARGO_TARGET_DIR, otherwise use OUT_DIR-relative
    let target_dir = env::var("CARGO_TARGET_DIR")
        .ok()
        .map(PathBuf::from)
        .unwrap_or_else(|| {
            PathBuf::from(env::var("OUT_DIR").unwrap())
                .parent()
                .and_then(|p| p.parent())
                .and_then(|p| p.parent())
                .expect("cannot derive target dir from OUT_DIR")
                .to_path_buf()
        });

    let status = Command::new("cargo")
        .args([
            "build",
            "--target",
            "x86_64-unknown-linux-musl",
            "--release",
            "--target-dir",
        ])
        .arg(&target_dir)
        .current_dir(&premount_src)
        .status()
        .unwrap_or_else(|e| {
            panic!("Failed to execute cargo command for premount-init: {}", e);
        });

    if !status.success() {
        panic!("premount-init build failed with status: {}", status);
    }

    let built = target_dir
        .join("x86_64-unknown-linux-musl/release/premount-init");
    if !built.exists() {
        panic!("premount-init binary not found after successful build at: {}", built.display());
    }

    fs::copy(&built, &premount_bin).unwrap_or_else(|e| {
        panic!("Failed to copy premount-init binary: {}", e);
    });
    println!("cargo:warning=premount-init built successfully");

    // Rebuild if premount-init source changes
    println!(
        "cargo:rerun-if-changed={}",
        premount_src.join("src/main.rs").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        premount_src.join("Cargo.toml").display()
    );

    // 2. Generate premount_ignore.rs from .czblignore
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let ignore_path = repo_root.join(".czblignore");
    let dest = out_dir.join("premount_ignore.rs");

    let mut patterns: Vec<(String, bool)> = Vec::new();

    if let Ok(f) = fs::File::open(&ignore_path) {
        let reader = std::io::BufReader::new(f);
        for line in reader.lines() {
            let line = match line {
                Ok(l) => l,
                Err(_) => continue,
            };
            let trimmed = line.trim();
            if trimmed.is_empty() || trimmed.starts_with('#') {
                continue;
            }
            let is_prefix = trimmed.ends_with('*');
            let name = if is_prefix {
                &trimmed[..trimmed.len() - 1]
            } else {
                trimmed
            };
            if name.is_empty() {
                continue;
            }
            patterns.push((name.to_uppercase(), is_prefix));
        }
    } else {
        println!(
            "cargo:warning=.czblignore not found at {}, using built-in defaults",
            ignore_path.display()
        );
        patterns.push(("MD5SUM".into(), true));
        patterns.push(("README".into(), true));
        patterns.push(("UBUNTU".into(), true));
        patterns.push(("AUTORUN.INF".into(), false));
    }

    let mut code = String::new();
    code.push_str("// AUTO-GENERATED by build.rs from .czblignore — DO NOT EDIT\n");
    code.push_str(
        "pub static PREMOUNT_IGNORE_PATTERNS: &[PremountIgnorePattern] = &[\n",
    );
    for (name, is_prefix) in &patterns {
        let escaped = name.escape_default().to_string();
        code.push_str(&format!(
            "    PremountIgnorePattern {{ name: b\"{}\", is_prefix: {} }},\n",
            escaped, is_prefix
        ));
    }
    code.push_str("];\n");
    code.push_str(
        "\npub struct PremountIgnorePattern {\n\
         \x20   pub name: &'static [u8],\n\
         \x20   pub is_prefix: bool,\n\
         }\n",
    );

    fs::write(&dest, &code).unwrap_or_else(|e| {
        panic!("Failed to write {}: {}", dest.display(), e);
    });

    println!("cargo:rerun-if-changed={}", ignore_path.display());
    println!("cargo:rerun-if-changed=src/");
    println!("cargo:rerun-if-changed=build.rs");
}