//! Build script for choosable-efi.
//!
//! 1. Builds `premount-init` (static ELF for /init.choosable) via musl.
//! 2. Reads `.czblignore` → emits `premount_ignore.rs`.

use std::env;
use std::fs;
use std::io::BufRead;
use std::path::PathBuf;
use std::process::Command;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let repo_root = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .expect("cannot find repo root");

    // 1. Build premount-init binary (static musl, runs as /init.choosable)
    let premount_src = repo_root.join("bootloader/premount-init");
    let premount_bin = manifest_dir.join("premount-init.bin");

    if premount_src.exists() {
        let status = Command::new("cargo")
            .args(["build", "--target", "x86_64-unknown-linux-musl", "--release"])
            .current_dir(&premount_src)
            .status();
        match status {
            Ok(s) if s.success() => {
                let built = premount_src
                    .join("target/x86_64-unknown-linux-musl/release/premount-init");
                if built.exists() {
                    fs::copy(&built, &premount_bin).unwrap_or_else(|e| {
                        panic!("Failed to copy premount-init binary: {}", e);
                    });
                    println!("cargo:warning=premount-init built successfully");
                } else {
                    println!("cargo:warning=premount-init binary not found after build");
                    // Create a minimal stub binary so include_bytes! doesn't fail
                    let stub = [0x7f, b'E', b'L', b'F']; // minimal ELF magic — will fail gracefully
                    fs::write(&premount_bin, stub).ok();
                }
            }
            Ok(s) => {
                println!("cargo:warning=premount-init build failed with status: {}", s);
            }
            Err(e) => {
                println!("cargo:warning=premount-init cargo command failed: {}", e);
            }
        }
    }

    // Rebuild if premount-init source changes
    println!(
        "cargo:rerun-if-changed={}",
        premount_src.join("src/main.rs").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        premount_src.join("Cargo.toml").display()
    );

    // 2. Generate premount_ignore.rs from .czblignore
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let ignore_path = repo_root.join(".czblignore");
    let dest = out_dir.join("premount_ignore.rs");

    let mut patterns: Vec<(String, bool)> = Vec::new();

    if let Ok(f) = fs::File::open(&ignore_path) {
        let reader = std::io::BufReader::new(f);
        for line in reader.lines() {
            let line = match line {
                Ok(l) => l,
                Err(_) => continue,
            };
            let trimmed = line.trim();
            if trimmed.is_empty() || trimmed.starts_with('#') {
                continue;
            }
            let is_prefix = trimmed.ends_with('*');
            let name = if is_prefix {
                &trimmed[..trimmed.len() - 1]
            } else {
                trimmed
            };
            if name.is_empty() {
                continue;
            }
            patterns.push((name.to_uppercase(), is_prefix));
        }
    } else {
        println!(
            "cargo:warning=.czblignore not found at {}, using built-in defaults",
            ignore_path.display()
        );
        patterns.push(("MD5SUM".into(), true));
        patterns.push(("README".into(), true));
        patterns.push(("UBUNTU".into(), true));
        patterns.push(("AUTORUN.INF".into(), false));
    }

    let mut code = String::new();
    code.push_str("// AUTO-GENERATED by build.rs from .czblignore — DO NOT EDIT\n");
    code.push_str(
        "pub static PREMOUNT_IGNORE_PATTERNS: &[PremountIgnorePattern] = &[\n",
    );
    for (name, is_prefix) in &patterns {
        let escaped = name.escape_default().to_string();
        code.push_str(&format!(
            "    PremountIgnorePattern {{ name: b\"{}\", is_prefix: {} }},\n",
            escaped, is_prefix
        ));
    }
    code.push_str("];\n");
    code.push_str(
        "\npub struct PremountIgnorePattern {\n\
         \x20   pub name: &'static [u8],\n\
         \x20   pub is_prefix: bool,\n\
         }\n",
    );

    fs::write(&dest, &code).unwrap_or_else(|e| {
        panic!("Failed to write {}: {}", dest.display(), e);
    });

    println!("cargo:rerun-if-changed={}", ignore_path.display());
    println!("cargo:rerun-if-changed=src/");
    println!("cargo:rerun-if-changed=build.rs");
}