//! Build script: generates bootloader binaries as Rust byte arrays.
//!
//! Output (via `$OUT_DIR/generated.rs`):
//! - `BOOT_IMG`: 440-byte MBR boot sector (x86-16 machine code)
//! - `STAGE2_BIN`: BIOS stage2 flat binary (16→32→64 trampoline + kernel)
//! - `EFI_BIN`: UEFI PE binary (cross-compiled x86_64-unknown-uefi)
//!
//! No external tools (nasm, gcc, linker script, objcopy) required.
//! All x86 machine code generated from pure Rust opcode tables.
//! ELF→flat conversion done in pure Rust.

use std::env;
use std::path::PathBuf;

const STAGE2_KERNEL_OFFSET: usize = 0x2000;
const STAGE2_GDT_PTR_OFF: u16 = 0x120;
const STAGE2_GDT_ENTS_OFF: u16 = 0x126;

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    std::fs::create_dir_all(out_dir.join("out")).ok();
    let dest = out_dir.join("generated.rs");

    let boot_img = build_mbr_boot_sector();
    let kernel_bin = build_kernel_binary(&out_dir);
    let stage2_bin = build_stage2_binary(&kernel_bin);
    let efi_bin = build_efi_binary(&out_dir);

    let code = format!(
        "// AUTO-GENERATED by build.rs — DO NOT EDIT\n\
         pub const BOOT_IMG: &[u8] = &{boot_img:?};\n\
         pub const STAGE2_BIN: &[u8] = &{stage2_bin:?};\n\
         pub const EFI_BIN: &[u8] = &{efi_bin:?};\n",
    );
    std::fs::write(&dest, &code).unwrap();

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=efi/src/");
    println!("cargo:rerun-if-changed=efi/Cargo.toml");
    println!("cargo:rerun-if-changed=kernel/src/");
    println!("cargo:rerun-if-changed=kernel/Cargo.toml");
}

// ═══════════════════════════════════════════════════════════════════════════
//  x86 instruction encoder
// ═══════════════════════════════════════════════════════════════════════════

struct CodeBuf {
    bytes: Vec<u8>,
}

impl CodeBuf {
    fn new() -> Self { CodeBuf { bytes: Vec::with_capacity(512) } }
    fn offset(&self) -> u16 { self.bytes.len() as u16 }
    fn emit(&mut self, b: u8) -> &mut Self { self.bytes.push(b); self }
    fn emit16(&mut self, w: u16) -> &mut Self { self.emit(w as u8).emit((w >> 8) as u8) }
    fn emit32(&mut self, d: u32) -> &mut Self {
        self.emit(d as u8).emit((d >> 8) as u8).emit((d >> 16) as u8).emit((d >> 24) as u8)
    }
    fn extend(&mut self, data: &[u8]) { self.bytes.extend_from_slice(data); }

    fn cli(&mut self) -> &mut Self { self.emit(0xFA) }
    fn sti(&mut self) -> &mut Self { self.emit(0xFB) }
    fn cld(&mut self) -> &mut Self { self.emit(0xFC) }
    fn nop(&mut self) -> &mut Self { self.emit(0x90) }
    fn ret(&mut self) -> &mut Self { self.emit(0xC3) }
    fn xor_ax_ax(&mut self) -> &mut Self { self.emit(0x31).emit(0xC0) }
    fn xor_bx_bx(&mut self) -> &mut Self { self.emit(0x31).emit(0xDB) }
    fn mov_ss_ax(&mut self) -> &mut Self { self.emit(0x8E).emit(0xD0) }
    fn mov_ds_ax(&mut self) -> &mut Self { self.emit(0x8E).emit(0xD8) }
    fn mov_es_ax(&mut self) -> &mut Self { self.emit(0x8E).emit(0xC0) }
    fn mov_sp(&mut self, v: u16) -> &mut Self { self.emit(0xBC).emit16(v) }
    fn mov_si(&mut self, v: u16) -> &mut Self { self.emit(0xBE).emit16(v) }
    fn mov_di(&mut self, v: u16) -> &mut Self { self.emit(0xBF).emit16(v) }
    fn mov_cx(&mut self, v: u16) -> &mut Self { self.emit(0xB9).emit16(v) }
    fn mov_bx(&mut self, v: u16) -> &mut Self { self.emit(0xBB).emit16(v) }
    fn mov_ah(&mut self, v: u8) -> &mut Self { self.emit(0xB4).emit(v) }
    fn mov_al(&mut self, v: u8) -> &mut Self { self.emit(0xB0).emit(v) }
    fn mov_mem8_dl(&mut self, addr: u16) -> &mut Self { self.emit(0x88).emit(0x16).emit16(addr) }
    fn mov_dl_mem16(&mut self, addr: u16) -> &mut Self { self.emit(0x8A).emit(0x16).emit16(addr) }
    fn mov_mem8_imm8(&mut self, addr: u16, v: u8) -> &mut Self { self.emit(0xC6).emit(0x06).emit16(addr).emit(v) }
    fn mov_mem16_imm16(&mut self, addr: u16, v: u16) -> &mut Self { self.emit(0xC7).emit(0x06).emit16(addr).emit16(v) }
    fn mov_mem32_imm32(&mut self, addr: u16, v: u32) -> &mut Self { self.emit(0x66).emit(0xC7).emit(0x06).emit16(addr).emit32(v) }
    fn cmp_mem8_imm8(&mut self, addr: u16, v: u8) -> &mut Self { self.emit(0x80).emit(0x3E).emit16(addr).emit(v) }
    fn cmp_bx(&mut self, v: u16) -> &mut Self { self.emit(0x81).emit(0xFB).emit16(v) }
    fn test_cl(&mut self, v: u8) -> &mut Self { self.emit(0xF6).emit(0xC1).emit(v) }
    fn shr_mem16_1(&mut self, addr: u16) -> &mut Self { self.emit(0xD1).emit(0x2E).emit16(addr) }
    fn rep_movsw(&mut self) -> &mut Self { self.emit(0xF3).emit(0xA5) }
    fn lodsb(&mut self) -> &mut Self { self.emit(0xAC) }
    fn test_al_al(&mut self) -> &mut Self { self.emit(0x08).emit(0xC0) }
    fn int(&mut self, n: u8) -> &mut Self { self.emit(0xCD).emit(n) }
    fn jmp_short(&mut self, rel: i8) -> &mut Self { self.emit(0xEB).emit(rel as u8) }
    fn jmp_far(&mut self, seg: u16, off: u16) -> &mut Self { self.emit(0xEA).emit16(off).emit16(seg) }
    fn pusha(&mut self) -> &mut Self { self.emit(0x60) }
    fn popa(&mut self) -> &mut Self { self.emit(0x61) }
    fn lgdt_mem16(&mut self, addr: u16) -> &mut Self { self.emit(0x0F).emit(0x01).emit(0x16).emit16(addr) }
    fn mov_eax_cr0(&mut self) -> &mut Self { self.emit(0x0F).emit(0x20).emit(0xC0) }
    fn mov_cr0_eax(&mut self) -> &mut Self { self.emit(0x0F).emit(0x22).emit(0xC0) }
    fn or_eax_imm32(&mut self, v: u32) -> &mut Self { self.emit(0x66).emit(0x0D).emit32(v) }
    fn jmp_far32(&mut self, sel: u16, off: u32) -> &mut Self { self.emit(0x66).emit(0xEA).emit32(off).emit16(sel) }

    fn jc_ph(&mut self) -> u16 { let p = self.offset(); self.emit(0x72).emit(0x00); p }
    fn jnc_ph(&mut self) -> u16 { let p = self.offset(); self.emit(0x73).emit(0x00); p }
    fn jne_ph(&mut self) -> u16 { let p = self.offset(); self.emit(0x75).emit(0x00); p }
    fn jz_ph(&mut self) -> u16 { let p = self.offset(); self.emit(0x74).emit(0x00); p }
    fn patch_rel8_here(&mut self, pos: u16) {
        let t = self.offset();
        self.bytes[pos as usize + 1] = (t as i32 - pos as i32 - 2) as i8 as u8;
    }
    fn call_rel16_ph(&mut self) -> u16 { let p = self.offset() + 1; self.emit(0xE8).emit16(0); p }
    fn label(&self) -> u16 { self.offset() }
}

// ═══════════════════════════════════════════════════════════════════════════
//  MBR (440 bytes)
// ═══════════════════════════════════════════════════════════════════════════

fn build_mbr_boot_sector() -> Vec<u8> {
    let mut c = CodeBuf::new();
    c.cli().xor_ax_ax().mov_ss_ax().mov_sp(0x7C00).mov_ds_ax().mov_es_ax().cld();
    c.mov_si(0x7C00).mov_di(0x0600).mov_cx(0x0100).rep_movsw();
    c.jmp_far(0x0000, 0x061E_u16);
    while c.offset() < 0x001E { c.nop(); }
    c.sti();

    let dn: u16 = 0x07B0; let ul: u16 = 0x07B1; let dsc: u16 = 0x07C2;
    let dll: u16 = 0x07C8; let da: u16 = 0x07C0; let cookie_addr: u16 = 0x7B00;

    c.mov_mem8_dl(dn);

    // Boot cookie check
    c.emit(0x66).emit(0xA1).emit16(cookie_addr);
    c.emit(0x66).emit(0x3D).emit32(0x544F4F42u32);
    let jne_normal = c.jne_ph();
    c.emit(0x66).emit(0xC7).emit(0x06).emit16(cookie_addr).emit32(0);
    c.mov_dl_mem16(dn).jmp_far(0x0000, 0x7C00);
    c.patch_rel8_here(jne_normal);

    c.mov_ah(0x41).mov_bx(0x55AA).int(0x13);
    let j1 = c.jc_ph();
    c.cmp_bx(0xAA55);
    let j2 = c.jne_ph();
    c.test_cl(0x01);
    let j3 = c.jz_ph();
    c.mov_mem8_imm8(ul, 1);
    c.patch_rel8_here(j1); c.patch_rel8_here(j2); c.patch_rel8_here(j3);
    c.mov_mem32_imm32(dll, 1).mov_mem32_imm32(dll + 4, 0);
    c.mov_mem16_imm16(dsc, 127);
    c.mov_mem16_imm16(0x07C0, 0x0010);
    c.mov_mem16_imm16(0x07C4, 0x7E00);
    c.mov_mem16_imm16(0x07C6, 0x0000);
    c.cmp_mem8_imm8(ul, 1);
    let j4 = c.jne_ph();
    c.mov_ah(0x42).mov_dl_mem16(dn).mov_si(da).int(0x13);
    let j5 = c.jnc_ph();
    c.shr_mem16_1(dsc);
    let j6 = c.jne_ph();
    c.patch_rel8_here(j4);
    c.mov_si(0x07B2);
    let cp = c.call_rel16_ph();
    let crp = c.offset();
    c.jmp_short(-2i8);
    c.patch_rel8_here(j6); c.patch_rel8_here(j5);
    c.mov_dl_mem16(dn).jmp_far(0x0000, 0x7E00);
    let pl = c.label();
    let ci = crp - 2;
    c.bytes[ci as usize] = (pl - crp) as u8;
    c.bytes[ci as usize + 1] = ((pl - crp) >> 8) as u8;
    c.pusha().mov_ah(0x0E).xor_bx_bx().lodsb().test_al_al();
    let pz = c.jz_ph();
    c.int(0x10).jmp_short(-9i8);
    c.popa().ret();
    c.patch_rel8_here(pz);
    while c.bytes.len() < 440 { c.emit(0x00); }
    c.bytes
}

// ═══════════════════════════════════════════════════════════════════════════
//  Stage2 — 16→32→64 trampoline + kernel
// ═══════════════════════════════════════════════════════════════════════════

fn build_stage2_binary(kernel: &[u8]) -> Vec<u8> {
    let mut c = CodeBuf::new();

    // 16-bit real mode entry
    c.cli().xor_ax_ax().mov_ss_ax().mov_sp(0x7E00);
    c.mov_mem8_dl(0x7DFE);

    // Enable A20 gate
    c.mov_al(0xD1).emit(0xE6).emit(0x64).mov_al(0xDF).emit(0xE6).emit(0x60);
    c.mov_cx(0xFFFF);
    let _ = c.label();
    c.emit(0xE2).emit(0xFE);
    c.mov_ah(0x24).mov_al(0x01).int(0x15);
    c.mov_al(0x02).emit(0xE6).emit(0x92);

    // GDT pseudo-descriptor
    while c.offset() < STAGE2_GDT_PTR_OFF { c.emit(0x90); }
    c.emit16(5 * 8 - 1);
    c.emit32(0x7E00 + STAGE2_GDT_ENTS_OFF as u32);

    // GDT entries
    while c.offset() < STAGE2_GDT_ENTS_OFF { c.emit(0x00); }
    c.emit32(0).emit32(0); // null
    c.emit16(0xFFFF).emit16(0x0000).emit(0x00).emit(0x9A).emit(0xCF).emit(0x00); // 32-bit code
    c.emit16(0xFFFF).emit16(0x0000).emit(0x00).emit(0x92).emit(0xCF).emit(0x00); // 32-bit data
    c.emit16(0x0000).emit16(0x0000).emit(0x00).emit(0x9A).emit(0x20).emit(0x00); // 64-bit code
    c.emit16(0x0000).emit16(0x0000).emit(0x00).emit(0x92).emit(0x00).emit(0x00); // 64-bit data

    let preamble_len = c.offset();

    // 32-bit trampoline: setup segments
    c.emit(0xB8).emit32(0x10);
    for &b in &[0x8E_u8, 0xD8, 0x8E, 0xC0, 0x8E, 0xE0, 0x8E, 0xE8, 0x8E, 0xD0] { c.emit(b); }
    c.emit(0xBC).emit32(0x0008_0000u32);

    // copy kernel
    c.emit(0xBE).emit32(0x9E00).emit(0xBF).emit32(0x100000);
    c.emit(0xB9).emit32(((kernel.len() + 3) / 4) as u32);
    c.emit(0xFC).emit(0xF3).emit(0xA5);

    // build page tables
    let pml4_phys: u32 = 0x90000; let pdpt_phys: u32 = 0x91000; let pd_phys: u32 = 0x92000;

    for &phys in &[pml4_phys, pdpt_phys] {
        c.emit(0xBF).emit32(phys).emit(0xB9).emit32(1024);
        c.emit(0x31).emit(0xC0).emit(0xF3).emit(0xAB);
    }

    c.emit(0xC7).emit(0x05).emit32(pml4_phys).emit32(pdpt_phys | 0x03);
    c.emit(0xC7).emit(0x05).emit32(pdpt_phys).emit32(pd_phys | 0x03);

    // Fill PD
    c.emit(0xBF).emit32(pd_phys).emit(0xB9).emit32(512).emit(0x31).emit(0xF6);
    let fl = c.offset() as usize;
    c.emit(0x89).emit(0xF0).emit(0xC1).emit(0xE0).emit(21);
    c.emit(0x0D).emit32(0x83).emit(0xAB);
    c.emit(0x31).emit(0xC0).emit(0xAB);
    c.emit(0x46).emit(0x49);
    let fj = c.offset();
    c.emit(0x75).emit(0x00);
    c.bytes[fj as usize + 1] = (fl as u32).wrapping_sub(fj as u32).wrapping_sub(2) as u8;

    // Enable PAE + Load CR3
    c.emit(0x0F).emit(0x20).emit(0xE0).emit(0x83).emit(0xC8).emit(0x20).emit(0x0F).emit(0x22).emit(0xE0);
    c.emit(0xB8).emit32(pml4_phys).emit(0x0F).emit(0x22).emit(0xD8);

    // Enable EFER.LME
    c.emit(0xB9).emit32(0xC000_0080u32).emit(0x0F).emit(0x32).emit(0x0D).emit32(0x100).emit(0x0F).emit(0x30);

    // Enable paging
    c.mov_eax_cr0().emit(0x0D).emit32(0x8000_0000u32).mov_cr0_eax();

    // Far jump to 64-bit kernel
    c.emit(0xEA).emit32(0x100000u32).emit16(0x18);

    // Patch 16-bit preamble
    let trampoline = c.bytes.split_off(preamble_len as usize);
    c.lgdt_mem16(0x7E00 + STAGE2_GDT_PTR_OFF);
    c.mov_eax_cr0().or_eax_imm32(1).mov_cr0_eax();
    c.jmp_far32(0x08, 0x7E00u32 + c.offset() as u32 + 8);
    c.bytes.extend_from_slice(&trampoline);

    while (c.offset() as usize) < STAGE2_KERNEL_OFFSET { c.emit(0x00); }
    c.extend(kernel);
    c.bytes
}

// ═══════════════════════════════════════════════════════════════════════════
//  Kernel cross-compilation + ELF→flat
// ═══════════════════════════════════════════════════════════════════════════

fn build_kernel_binary(out_dir: &PathBuf) -> Vec<u8> {
    let kdir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap()).join("kernel");
    let ktarget = out_dir.join("kernel-target");
    let _ = std::fs::remove_dir_all(kdir.join("target"));

    println!("cargo:warning=Building kernel for x86_64-unknown-none...");
    let status = std::process::Command::new("cargo")
        .args(["build", "--target", "x86_64-unknown-none", "--release"])
        .env_remove("RUSTFLAGS").env_remove("CARGO_ENCODED_RUSTFLAGS")
        .env("RUSTFLAGS", "-C link-arg=--image-base=0x100000 -C link-arg=-no-pie -C link-arg=-Ttext=0x100000 -C relocation-model=static")
        .arg("--target-dir").arg(&ktarget)
        .current_dir(&kdir)
        .status();

    match status {
        Ok(s) if s.success() => {}
        Ok(s) => panic!("Kernel build failed with exit code {:?}", s.code()),
        Err(e) => panic!("Kernel build failed to start: {}", e),
    }

    let elf_path = ktarget.join("x86_64-unknown-none/release/choosable-kernel");
    std::fs::read(&elf_path).map(|elf| {
        println!("cargo:warning=Kernel ELF size: {} bytes", elf.len());
        extract_flat_from_elf(&elf)
    }).unwrap_or_else(|e| {
        println!("cargo:warning=Read kernel ELF: {}", e);
        vec![0; 512]
    })
}

fn extract_flat_from_elf(elf: &[u8]) -> Vec<u8> {
    if elf.len() < 64 { return vec![0; 512]; }
    let e_phoff = u64::from_le_bytes(elf[32..40].try_into().unwrap());
    let e_phnum = u16::from_le_bytes(elf[56..58].try_into().unwrap());

    let mut lo_segments: Vec<_> = (0..e_phnum as u64)
        .filter_map(|i| {
            let off = (e_phoff + i * 56) as usize;
            if off + 56 > elf.len() { return None; }
            if u32::from_le_bytes(elf[off..off + 4].try_into().unwrap()) != 1 { return None; }
            Some((
                u64::from_le_bytes(elf[off + 16..off + 24].try_into().unwrap()),
                u64::from_le_bytes(elf[off + 8..off + 16].try_into().unwrap()) as usize,
                u64::from_le_bytes(elf[off + 32..off + 40].try_into().unwrap()) as usize,
            ))
        })
        .collect();

    lo_segments.retain(|(va, _, sz)| *va >= 0x1000 || *sz >= 0x1000);
    if lo_segments.is_empty() { return vec![0; 512]; }

    lo_segments.sort_by_key(|s| s.0);
    let min_vaddr = lo_segments[0].0;
    let max_end = lo_segments.iter().map(|(va, _, sz)| (va - min_vaddr) as usize + sz).max().unwrap_or(512);
    let mut flat = vec![0u8; max_end.max(512)];

    for (vaddr, foff, fsz) in &lo_segments {
        let dest_off = (vaddr - min_vaddr) as usize;
        if *foff < elf.len() {
            let src_len = (*fsz).min(elf.len() - *foff);
            let copy_len = src_len.min(flat.len() - dest_off);
            flat[dest_off..dest_off + copy_len].copy_from_slice(&elf[*foff..*foff + copy_len]);
        }
    }
    flat
}

// ═══════════════════════════════════════════════════════════════════════════
//  EFI (cross-compiled)
// ═══════════════════════════════════════════════════════════════════════════

fn build_efi_binary(out_dir: &PathBuf) -> Vec<u8> {
    let efi_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap()).join("efi");
    let efi_target = out_dir.join("efi-target");
    let _ = std::fs::remove_dir_all(efi_dir.join("target"));
    let _ = std::fs::remove_dir_all(&efi_target);

    println!("cargo:warning=Building EFI for x86_64-unknown-uefi...");
    let s = std::process::Command::new("cargo")
        .args(["build", "--target", "x86_64-unknown-uefi", "--release"])
        .arg("--target-dir").arg(&efi_target)
        .current_dir(&efi_dir)
        .status();

    match s {
        Ok(st) if st.success() => {}
        _ => panic!("EFI build failed"),
    }
    std::fs::read(efi_target.join("x86_64-unknown-uefi/release/choosable-efi.efi"))
        .unwrap_or_else(|_| vec![0; 512])
}