//! Build script: generates bootloader binaries as Rust byte arrays.
//!
//! Output (via `$OUT_DIR/generated.rs`):
//! - `BOOT_IMG`: 440-byte MBR boot sector (x86-16 machine code)
//! - `STAGE2_BIN`: BIOS stage2 flat binary (16→32→64 trampoline + kernel)
//! - `EFI_BIN`: UEFI PE binary (cross-compiled x86_64-unknown-uefi)
//!
//! No external tools (nasm, gcc, linker script, objcopy) required.
//! All x86 machine code generated from pure Rust opcode tables.
//! ELF→flat conversion done in pure Rust.

use std::env;
use std::fs;
use std::path::PathBuf;

// ── Stage2 layout constants ─────────────────────────────────────────────
const STAGE2_KERNEL_OFFSET: usize = 0x2000; // kernel flat binary starts here
const STAGE2_PROT_OFFSET: u16 = 0xA0; // 32-bit protected mode entry
const STAGE2_PML4_OFFSET: u16 = 0x200; // PML4 page table (page-aligned → phys 0x8000)
const STAGE2_PDPT_OFFSET: u16 = 0x400; // PDPT (phys 0x8200)
const STAGE2_PD_OFFSET: u16 = 0x600; // Page Directory (phys 0x8400, 512 entries)
const STAGE2_GDT_PTR_OFF: u16 = 0x120; // GDT pseudo-descriptor
const STAGE2_GDT_ENTS_OFF: u16 = 0x126; // GDT entries

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    fs::create_dir_all(out_dir.join("out")).ok();
    let dest = out_dir.join("generated.rs");

    let boot_img = build_mbr_boot_sector();
    let kernel_bin = build_kernel_binary(&out_dir);
    let stage2_bin = build_stage2_binary(&kernel_bin);
    let efi_bin = build_efi_binary(&out_dir);

    let code = format!(
        r#"// AUTO-GENERATED by build.rs — DO NOT EDIT
pub const BOOT_IMG: &[u8] = &{boot_img:?};
pub const STAGE2_BIN: &[u8] = &{stage2_bin:?};
pub const EFI_BIN: &[u8] = &{efi_bin:?};
"#,
    );
    fs::write(&dest, &code).unwrap();

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=efi/src/main.rs");
    println!("cargo:rerun-if-changed=efi/Cargo.toml");
    println!("cargo:rerun-if-changed=kernel/src/main.rs");
    println!("cargo:rerun-if-changed=kernel/Cargo.toml");
}

// ═══════════════════════════════════════════════════════════════════════════
//  x86 instruction encoder
// ═══════════════════════════════════════════════════════════════════════════

struct CodeBuf { bytes: Vec<u8> }

impl CodeBuf {
    fn new() -> Self { CodeBuf { bytes: Vec::with_capacity(512) } }
    fn offset(&self) -> u16 { self.bytes.len() as u16 }
    fn emit(&mut self, b: u8) -> &mut Self { self.bytes.push(b); self }
    fn emit16(&mut self, w: u16) -> &mut Self { self.emit(w as u8).emit((w >> 8) as u8) }
    fn emit32(&mut self, d: u32) -> &mut Self {
        self.emit(d as u8).emit((d>>8) as u8).emit((d>>16) as u8).emit((d>>24) as u8)
    }
    fn emit64(&mut self, q: u64) -> &mut Self {
        self.emit32(q as u32).emit32((q>>32) as u32)
    }

    fn cli(&mut self) -> &mut Self { self.emit(0xFA) }
    fn sti(&mut self) -> &mut Self { self.emit(0xFB) }
    fn cld(&mut self) -> &mut Self { self.emit(0xFC) }
    fn hlt(&mut self) -> &mut Self { self.emit(0xF4) }
    fn nop(&mut self) -> &mut Self { self.emit(0x90) }
    fn ret(&mut self) -> &mut Self { self.emit(0xC3) }
    fn xor_ax_ax(&mut self) -> &mut Self { self.emit(0x31).emit(0xC0) }
    fn xor_bx_bx(&mut self) -> &mut Self { self.emit(0x31).emit(0xDB) }
    fn mov_ss_ax(&mut self) -> &mut Self { self.emit(0x8E).emit(0xD0) }
    fn mov_ds_ax(&mut self) -> &mut Self { self.emit(0x8E).emit(0xD8) }
    fn mov_es_ax(&mut self) -> &mut Self { self.emit(0x8E).emit(0xC0) }
    fn mov_sp(&mut self, v: u16) -> &mut Self { self.emit(0xBC).emit16(v) }
    fn mov_si(&mut self, v: u16) -> &mut Self { self.emit(0xBE).emit16(v) }
    fn mov_di(&mut self, v: u16) -> &mut Self { self.emit(0xBF).emit16(v) }
    fn mov_cx(&mut self, v: u16) -> &mut Self { self.emit(0xB9).emit16(v) }
    fn mov_bx(&mut self, v: u16) -> &mut Self { self.emit(0xBB).emit16(v) }
    fn mov_ah(&mut self, v: u8) -> &mut Self { self.emit(0xB4).emit(v) }
    fn mov_al(&mut self, v: u8) -> &mut Self { self.emit(0xB0).emit(v) }
    fn mov_mem8_dl(&mut self, addr: u16) -> &mut Self { self.emit(0x88).emit(0x16).emit16(addr) }
    fn mov_dl_mem16(&mut self, addr: u16) -> &mut Self { self.emit(0x8A).emit(0x16).emit16(addr) }
    fn mov_mem8_imm8(&mut self, addr: u16, v: u8) -> &mut Self {
        self.emit(0xC6).emit(0x06).emit16(addr).emit(v)
    }
    fn mov_mem16_imm16(&mut self, addr: u16, v: u16) -> &mut Self {
        self.emit(0xC7).emit(0x06).emit16(addr).emit16(v)
    }
    fn mov_mem32_imm32(&mut self, addr: u16, v: u32) -> &mut Self {
        self.emit(0x66).emit(0xC7).emit(0x06).emit16(addr).emit32(v)
    }
    fn cmp_mem8_imm8(&mut self, addr: u16, v: u8) -> &mut Self {
        self.emit(0x80).emit(0x3E).emit16(addr).emit(v)
    }
    fn cmp_bx(&mut self, v: u16) -> &mut Self { self.emit(0x81).emit(0xFB).emit16(v) }
    fn test_cl(&mut self, v: u8) -> &mut Self { self.emit(0xF6).emit(0xC1).emit(v) }
    fn shr_mem16_1(&mut self, addr: u16) -> &mut Self { self.emit(0xD1).emit(0x2E).emit16(addr) }
    fn rep_movsw(&mut self) -> &mut Self { self.emit(0xF3).emit(0xA5) }
    fn lodsb(&mut self) -> &mut Self { self.emit(0xAC) }
    fn test_al_al(&mut self) -> &mut Self { self.emit(0x08).emit(0xC0) }
    fn int(&mut self, n: u8) -> &mut Self { self.emit(0xCD).emit(n) }
    fn jmp_short(&mut self, rel: i8) -> &mut Self { self.emit(0xEB).emit(rel as u8) }
    fn jmp_far(&mut self, seg: u16, off: u16) -> &mut Self { self.emit(0xEA).emit16(off).emit16(seg) }
    fn pusha(&mut self) -> &mut Self { self.emit(0x60) }
    fn popa(&mut self) -> &mut Self { self.emit(0x61) }
    fn lgdt_mem16(&mut self, addr: u16) -> &mut Self { self.emit(0x0F).emit(0x01).emit(0x16).emit16(addr) }
    fn mov_eax_cr0(&mut self) -> &mut Self { self.emit(0x0F).emit(0x20).emit(0xC0) }
    fn mov_cr0_eax(&mut self) -> &mut Self { self.emit(0x0F).emit(0x22).emit(0xC0) }
    fn or_eax_imm32(&mut self, v: u32) -> &mut Self { self.emit(0x66).emit(0x0D).emit32(v) }
    fn jmp_far32(&mut self, sel: u16, off: u32) -> &mut Self { self.emit(0x66).emit(0xEA).emit32(off).emit16(sel) }
    // Conditional jumps with placeholder
    fn jc_ph(&mut self) -> u16 { let p=self.offset(); self.emit(0x72).emit(0x00); p }
    fn jnc_ph(&mut self) -> u16 { let p=self.offset(); self.emit(0x73).emit(0x00); p }
    fn jne_ph(&mut self) -> u16 { let p=self.offset(); self.emit(0x75).emit(0x00); p }
    fn jz_ph(&mut self) -> u16 { let p=self.offset(); self.emit(0x74).emit(0x00); p }
    fn patch_rel8_here(&mut self, pos: u16) {
        let t = self.offset(); self.bytes[pos as usize+1] = (t as i32 - pos as i32 - 2) as i8 as u8;
    }
    fn call_rel16_ph(&mut self) -> u16 { let p=self.offset()+1; self.emit(0xE8).emit16(0); p } // returns offset of rel16 field
    fn label(&self) -> u16 { self.offset() }
    fn extend(&mut self, data: &[u8]) { self.bytes.extend_from_slice(data); }
}

// ═══════════════════════════════════════════════════════════════════════════
//  MBR (440 bytes) — unchanged
// ═══════════════════════════════════════════════════════════════════════════

fn build_mbr_boot_sector() -> Vec<u8> {
    let mut c = CodeBuf::new();
    c.cli(); c.xor_ax_ax(); c.mov_ss_ax(); c.mov_sp(0x7C00); c.mov_ds_ax(); c.mov_es_ax(); c.cld();
    c.mov_si(0x7C00); c.mov_di(0x0600); c.mov_cx(0x0100); c.rep_movsw();
    c.jmp_far(0x0000, 0x061E_u16);
    while c.offset() < 0x001E { c.nop(); }
    c.sti();
    let dn: u16 = 0x07B0;
    let ul: u16 = 0x07B1;
    let dsc: u16 = 0x07C2;
    let dll: u16 = 0x07C8;
    let da: u16 = 0x07C0;
    let cookie_addr: u16 = 0x7DF0;

    c.mov_mem8_dl(dn);

    // ══ Check boot cookie at 0x7DF0 ═════════════════════════════════
    // If "BOOT" magic (0x544F4F42) is present, jump directly to 0x7C00
    // This is a warm reboot from the kernel after loading an ISO boot image.
    // MOV EAX, [cookie_addr]  (32-bit load: 66 A1 + addr16)
    c.emit(0x66).emit(0xA1).emit16(cookie_addr); // MOV EAX, [cookie_addr]
    // CMP EAX, 0x544F4F42
    c.emit(0x66).emit(0x3D).emit32(0x544F4F42u32); // CMP EAX, BOOT_COOKIE_MAGIC
    let jne_normal = c.jne_ph();
    // Boot cookie found! DL already has disk number. Jump to 0x7C00.
    // First clear the cookie so subsequent resets don't loop
    c.emit(0x66).emit(0xC7).emit(0x06).emit16(cookie_addr).emit32(0); // MOV DWORD [cookie], 0
    c.mov_dl_mem16(dn); // restore DL (may have been clobbered)
    c.jmp_far(0x0000, 0x7C00);

    // ── Normal boot path ────────────────────────────────────────────
    c.patch_rel8_here(jne_normal);

    c.mov_ah(0x41); c.mov_bx(0x55AA); c.int(0x13);
    let j1=c.jc_ph(); c.cmp_bx(0xAA55); let j2=c.jne_ph(); c.test_cl(0x01); let j3=c.jz_ph();
    c.mov_mem8_imm8(ul, 1);
    c.patch_rel8_here(j1); c.patch_rel8_here(j2); c.patch_rel8_here(j3);
    c.mov_mem32_imm32(dll,1); c.mov_mem16_imm16(dsc,127);
    c.cmp_mem8_imm8(ul,1); let j4=c.jne_ph();
    c.mov_ah(0x42); c.mov_dl_mem16(dn); c.mov_si(da); c.int(0x13);
    let j5=c.jnc_ph(); c.shr_mem16_1(dsc); let j6=c.jne_ph();
    c.patch_rel8_here(j4); c.mov_si(0x07B2);
    let cp=c.call_rel16_ph(); let crp=c.offset(); c.jmp_short(-2i8);
    c.patch_rel8_here(j6);
    c.patch_rel8_here(j5); c.mov_dl_mem16(dn); c.jmp_far(0x0000,0x7E00);
    let pl=c.label(); let ci=crp-2;
    c.bytes[ci as usize+1]=(pl-crp) as u8; c.bytes[ci as usize+2]=((pl-crp)>>8) as u8;
    c.pusha(); c.mov_ah(0x0E); c.xor_bx_bx(); c.lodsb(); c.test_al_al();
    let pz=c.jz_ph(); c.int(0x10); c.jmp_short(-9i8); c.popa(); c.ret(); c.patch_rel8_here(pz);
    while c.bytes.len()<440 { c.emit(0x00); }
    c.bytes
}

// ═══════════════════════════════════════════════════════════════════════════
//  Stage2 — 16→32→64 trampoline + kernel
// ═══════════════════════════════════════════════════════════════════════════

fn build_stage2_binary(kernel: &[u8]) -> Vec<u8> {
    // Layout (physical addresses, stage2 loaded at 0x7E00):
    //  offset 0x000 – 0x0?? : 16-bit real-mode entry
    //  offset 0x120         : GDT pseudo-descriptor (limit + base)
    //  offset 0x126         : GDT entries (5 × 8 = 40 bytes → ends at 0x14E)
    //  0x14E+               : 32-bit protected mode code (calculated dynamically)
    //  offset 0x200         : PML4 (page-aligned, zeroed by code)
    //  offset 0x400         : PDPT
    //  offset 0x600         : PD
    //  offset 0x2000        : kernel flat binary
    // ────────────────────────────────────────────────────────────────
    // The GDT pseudo-descriptor and entries are placed at fixed offsets
    // so the 16-bit real-mode code can refer to them by absolute address.
    // The 32-bit code MUST come immediately AFTER the GDT entries because
    // we emit GDT first (fixed offsets), then 32-bit code, then page tables,
    // then kernel.  The 16-bit entry calculates the 32-bit entry point as
    //   prot_entry = 0x7E00 + (current offset right after GDT entries).
    //
    // In 32-bit protected mode there is NO 0x66 prefix — the default
    // operand size in a 32-bit code segment is 32 bits.  Adding 0x66
    // would switch the instruction to 16-bit operands, which is wrong.
    // ────────────────────────────────────────────────────────────────

    let mut c = CodeBuf::new();

    // ── 16-bit real mode entry (phys 0x7E00) ───────────────────────
    c.cli();
    c.mov_mem8_dl(0x7DFE); // save disk number
    // Enable A20 (keyboard controller method — safe, no INT 15h needed)
    c.mov_al(0xD1); c.emit(0xE6).emit(0x64);
    c.mov_al(0xDF); c.emit(0xE6).emit(0x60);

    // ── GDT pseudo-descriptor (must be at STAGE2_GDT_PTR_OFF) ──────
    while c.offset() < STAGE2_GDT_PTR_OFF { c.emit(0x90); }
    c.emit16(5 * 8 - 1);                         // limit
    c.emit32(0x7E00 + STAGE2_GDT_ENTS_OFF as u32); // base

    // ── GDT entries (at STAGE2_GDT_ENTS_OFF) ────────────────────────
    while c.offset() < STAGE2_GDT_ENTS_OFF { c.emit(0x00); }
    // [0] null descriptor
    c.emit32(0); c.emit32(0);
    // [1] 32-bit code (selector 0x08): base=0, limit=4 GiB, D=1
    c.emit16(0xFFFF); c.emit16(0x0000); c.emit(0x00); c.emit(0x9A); c.emit(0xCF); c.emit(0x00);
    // [2] 32-bit data (selector 0x10): base=0, limit=4 GiB, writable
    c.emit16(0xFFFF); c.emit16(0x0000); c.emit(0x00); c.emit(0x92); c.emit(0xCF); c.emit(0x00);
    // [3] 64-bit code (selector 0x18): L=1, D=0
    c.emit16(0x0000); c.emit16(0x0000); c.emit(0x00); c.emit(0x9A); c.emit(0x20); c.emit(0x00);
    // [4] 64-bit data (selector 0x20)
    c.emit16(0x0000); c.emit16(0x0000); c.emit(0x00); c.emit(0x92); c.emit(0x00); c.emit(0x00);

    // ── 32-bit protected mode entry (immediately after GDT entries) ─
    // Record the physical address so the 16-bit code can far-jump here.
    let prot32_phys = 0x7E00u32 + c.offset() as u32;

    // Back in the 16-bit code: load GDT, set PE, far-jump to prot32
    // (We insert this BEFORE the 16-bit code that is already emitted,
    //  so we use a branch-past pattern.  Instead, we just write the
    //  LGDT / MOV CR0 / JMP FAR *here* because the 16-bit code hasn't
    //  been fully emitted yet — the GDT is written, but the far jump
    //  target wasn't known until now.  We'll patch the jmp_far32 into
    //  its correct position in the 16-bit preamble.)

    // Rewind: the 16-bit preamble (CLI … enable A20) is already in
    // `c.bytes`.  Now we append LGDT + PE enable + far-jump right after
    // the existing 16-bit code, using `prot32_phys` which is now known.
    let preamble_len = c.offset();

    // Build the 32-bit trampoline at the current position.
    // ── setup segments ──────────────────────────────────────────────
    // MOV EAX, 0x10  (B8 10 00 00 00)  -- no 0x66, default 32-bit
    c.emit(0xB8).emit32(0x10);
    // MOV DS, AX   (8E D8)
    c.emit(0x8E).emit(0xD8);
    // MOV ES, AX   (8E C0)
    c.emit(0x8E).emit(0xC0);
    // MOV FS, AX   (8E E0)
    c.emit(0x8E).emit(0xE0);
    // MOV GS, AX   (8E E8)
    c.emit(0x8E).emit(0xE8);
    // MOV SS, AX   (8E D0)
    c.emit(0x8E).emit(0xD0);
    // MOV ESP, 0x80000  (BC 00 00 08 00)
    c.emit(0xBC).emit32(0x0008_0000u32);

    // ── build page tables ───────────────────────────────────────────
    // PML4 at phys 0x8000 (binary offset 0x200)
    let pml4_phys: u32 = 0x8000;
    let pdpt_phys: u32 = 0x8200;
    let pd_phys: u32   = 0x8400;

    // Zero PML4 (EDI = pml4_phys, ECX = 1024, EAX = 0, REP STOSD)
    c.emit(0xBF).emit32(pml4_phys);       // MOV EDI, pml4_phys
    c.emit(0xB9).emit32(1024);             // MOV ECX, 1024
    c.emit(0x31).emit(0xC0);               // XOR EAX, EAX
    let z1 = c.offset() as usize;
    c.emit(0xAB);                          // STOSD
    c.emit(0x49);                          // DEC ECX
    let z1j = c.offset(); c.emit(0x75).emit(0x00);
    c.bytes[z1j as usize+1] = (z1 as u32).wrapping_sub(z1j as u32).wrapping_sub(2) as u8;

    // Zero PDPT
    c.emit(0xBF).emit32(pdpt_phys);
    c.emit(0xB9).emit32(1024);
    c.emit(0x31).emit(0xC0);
    let z2 = c.offset() as usize;
    c.emit(0xAB); c.emit(0x49);
    let z2j = c.offset(); c.emit(0x75).emit(0x00);
    c.bytes[z2j as usize+1] = (z2 as u32).wrapping_sub(z2j as u32).wrapping_sub(2) as u8;

    // PML4[0] = pdpt_phys | 0x03
    c.emit(0xC7).emit(0x05).emit32(pml4_phys).emit32(pdpt_phys | 0x03);

    // PDPT[0] = pd_phys | 0x03
    c.emit(0xC7).emit(0x05).emit32(pdpt_phys).emit32(pd_phys | 0x03);

    // Fill PD with 512 × 2 MiB entries: PD[i] = (i*2MB) | 0x83
    c.emit(0xBF).emit32(pd_phys);           // MOV EDI, pd_phys
    c.emit(0xB9).emit32(512);               // MOV ECX, 512
    c.emit(0x31).emit(0xF6);                // XOR ESI, ESI
    let fl = c.offset() as usize;
    c.emit(0x89).emit(0xF0);                // MOV EAX, ESI
    c.emit(0xC1).emit(0xE0).emit(21);       // SHL EAX, 21
    c.emit(0x83).emit(0xC8).emit(0x83);     // OR EAX, 0x83
    c.emit(0xAB);                            // STOSD (lo 32)
    c.emit(0x31).emit(0xC0);                // XOR EAX, EAX
    c.emit(0xAB);                            // STOSD (hi 32)
    c.emit(0x46);                            // INC ESI
    c.emit(0x49);                            // DEC ECX
    let fj = c.offset(); c.emit(0x75).emit(0x00);
    c.bytes[fj as usize+1] = (fl as u32).wrapping_sub(fj as u32).wrapping_sub(2) as u8;

    // Enable PAE (CR4.PAE = bit 5)
    c.emit(0x0F).emit(0x20).emit(0xE0);     // MOV EAX, CR4
    c.emit(0x83).emit(0xC8).emit(0x20);      // OR EAX, 0x20
    c.emit(0x0F).emit(0x22).emit(0xE0);     // MOV CR4, EAX

    // Load CR3
    c.emit(0xB8).emit32(pml4_phys);          // MOV EAX, pml4
    c.emit(0x0F).emit(0x22).emit(0xD8);     // MOV CR3, EAX

    // Enable EFER.LME via MSR 0xC0000080
    c.emit(0xB9).emit32(0xC000_0080u32);     // MOV ECX, 0xC0000080
    c.emit(0x0F).emit(0x32);                 // RDMSR
    c.emit(0x0D).emit32(0x100);              // OR EAX, 0x100
    c.emit(0x0F).emit(0x30);                 // WRMSR

    // Enable paging (CR0.PG | CR0.PE) — PE already set
    // CR0 |= 0x80000000
    c.emit(0x0F).emit(0x20).emit(0xC0);     // MOV EAX, CR0
    c.emit(0x0D).emit32(0x8000_0000u32);     // OR EAX, 0x80000000
    c.emit(0x0F).emit(0x22).emit(0xC0);     // MOV CR0, EAX

    // Far jump to 64-bit kernel entry (selector 0x18)
    // We're in 32-bit compat mode.  Opcode EA + 32-bit offset + 16-bit sel
    // is legal — offset truncated to 32 bits, which is fine since kernel < 4 GiB.
    let kernel_phys = (0x7E00u64 + STAGE2_KERNEL_OFFSET as u64) as u32;
    c.emit(0xEA).emit32(kernel_phys).emit16(0x18);

    // ── Patch the 16-bit preamble to far-jump to the 32-bit code ────
    // The 16-bit code occupies `c.bytes[0..preamble_len]`.
    // We need to insert LGDT / MOV CR0 / JMP FAR32 right after the A20 enable.
    // Save the 32-bit trampoline portion, put it aside, then rebuild
    // the 16-bit preamble with the jump inserted.
    let trampoline = c.bytes.split_off(preamble_len as usize);
    // Now c.bytes contains only the 16-bit preamble + GDT.
    // Append LGDT + PE + far-jump:
    c.lgdt_mem16(0x7E00 + STAGE2_GDT_PTR_OFF);
    c.mov_eax_cr0();
    c.or_eax_imm32(1);
    c.mov_cr0_eax();                         // CR0.PE = 1 → protected mode
    c.jmp_far32(0x08, prot32_phys);         // far jump to 32-bit selector + trampoline

    // Re-append the trampoline after the patched preamble.
    c.bytes.extend_from_slice(&trampoline);

    // Pad to STAGE2_KERNEL_OFFSET, then append kernel flat binary.
    while (c.offset() as usize) < STAGE2_KERNEL_OFFSET { c.emit(0x00); }
    c.extend(kernel);

    c.bytes
}

// ═══════════════════════════════════════════════════════════════════════════
//  Kernel cross-compilation + ELF→flat
// ═══════════════════════════════════════════════════════════════════════════

fn build_kernel_binary(out_dir: &PathBuf) -> Vec<u8> {
    let kdir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap()).join("kernel");
    let ktarget = out_dir.join("kernel-target");

    println!("cargo:warning=Building kernel for x86_64-unknown-none...");
    let status = std::process::Command::new("cargo")
        .args(&["build", "--target", "x86_64-unknown-none", "--release"])
        .arg("--target-dir").arg(&ktarget)
        .current_dir(&kdir)
        .status();

    match status {
        Ok(s) if s.success() => {}
        Ok(s) => { println!("cargo:warning=Kernel build exit {:?}", s.code()); return vec![0; 512]; }
        Err(e) => { println!("cargo:warning=Kernel build error: {}", e); return vec![0; 512]; }
    }

    let elf_path = ktarget.join("x86_64-unknown-none/release/choosable-kernel");
    match fs::read(&elf_path) {
        Ok(elf) => {
            println!("cargo:warning=Kernel ELF size: {} bytes", elf.len());
            extract_flat_from_elf(&elf)
        }
        Err(e) => { println!("cargo:warning=Read kernel ELF: {}", e); vec![0; 512] }
    }
}

fn extract_flat_from_elf(elf: &[u8]) -> Vec<u8> {
    if elf.len() < 64 { return vec![0;512]; }

    // Parse ELF64 header
    let e_phoff = u64::from_le_bytes(elf[32..40].try_into().unwrap());
    let e_phnum = u16::from_le_bytes(elf[56..58].try_into().unwrap());

    let mut lo_segments: Vec<(u64, usize, usize)> = Vec::new(); // (vaddr, file_offset, file_size)
    for i in 0..e_phnum as u64 {
        let off = (e_phoff + i * 56) as usize;
        if off + 56 > elf.len() { break; }
        let p_type = u32::from_le_bytes(elf[off..off+4].try_into().unwrap());
        if p_type != 1 { continue; } // PT_LOAD
        let p_offset = u64::from_le_bytes(elf[off+8..off+16].try_into().unwrap());
        let p_vaddr = u64::from_le_bytes(elf[off+16..off+24].try_into().unwrap());
        let p_filesz = u64::from_le_bytes(elf[off+32..off+40].try_into().unwrap());
        lo_segments.push((p_vaddr, p_offset as usize, p_filesz as usize));
    }

    if lo_segments.is_empty() { return vec![0;512]; }
    lo_segments.sort_by_key(|s| s.0);

    let min_vaddr = lo_segments[0].0;

    // Find max end address
    let max_end = lo_segments.iter().map(|(va, _, sz)| (va - min_vaddr) as usize + sz).max().unwrap_or(512);
    let mut flat = vec![0u8; max_end.max(512)];

    for (vaddr, foff, fsz) in &lo_segments {
        let dest_off = (vaddr - min_vaddr) as usize;
        let copy_end = (dest_off + fsz).min(flat.len());
        let src_end = (foff + fsz).min(elf.len());
        let copy_len = copy_end - dest_off;
        flat[dest_off..copy_end].copy_from_slice(&elf[*foff..src_end]);
    }

    flat
}

// ═══════════════════════════════════════════════════════════════════════════
//  EFI (cross-compiled)
// ═══════════════════════════════════════════════════════════════════════════

fn build_efi_binary(out_dir: &PathBuf) -> Vec<u8> {
    let efi_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap()).join("efi");
    let efi_target = out_dir.join("efi-target");

    println!("cargo:warning=Building EFI for x86_64-unknown-uefi...");
    let s = std::process::Command::new("cargo")
        .args(&["build", "--target", "x86_64-unknown-uefi", "--release"])
        .arg("--target-dir").arg(&efi_target)
        .current_dir(&efi_dir).status();

    match s {
        Ok(st) if st.success() => {}
        _ => { println!("cargo:warning=EFI build failed, placeholder"); return vec![0;512]; }
    }
    let path = efi_target.join("x86_64-unknown-uefi/release/choosable-efi.efi");
    fs::read(&path).unwrap_or_else(|_| vec![0;512])
}